/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.DTOGeneratorCodePlug+<GeneratorDTOModelAsync>d__8.MoveNext */

namespace MateralReleaseCenter.DeployServer.Abstractions.DTO.DefaultData;

/// <summary>
/// 默认数据数据传输模型
/// </summary>
public partial class DefaultDataDTO : DefaultDataListDTO, IDTO
{
}
