global using Materal.Abstractions;
global using Materal.Extensions.DependencyInjection;
global using Materal.MergeBlock.Abstractions;
global using Materal.MergeBlock.Abstractions.Models;
global using Materal.MergeBlock.Abstractions.Services;
global using Materal.MergeBlock.Application.Abstractions.Services;
global using Materal.MergeBlock.Web.Abstractions.Controllers;
global using Materal.Utils.AutoMapper;
global using Materal.Utils.Enums;
global using Materal.Utils.Extensions;
global using Materal.Utils.Models;
global using MateralReleaseCenter.Core.Abstractions;
global using MateralReleaseCenter.Core.Application;
global using MateralReleaseCenter.DeployServer.Abstractions;
global using MateralReleaseCenter.DeployServer.Abstractions.Controllers;
global using MateralReleaseCenter.DeployServer.Abstractions.Domain;
global using MateralReleaseCenter.DeployServer.Abstractions.Enums;
global using MateralReleaseCenter.DeployServer.Abstractions.Repositories;
global using MateralReleaseCenter.DeployServer.Abstractions.Services;
global using MateralReleaseCenter.DeployServer.Application;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using System.ComponentModel.DataAnnotations;
global using System.Linq;
global using System.Linq.Expressions;

[assembly: MergeBlockAssembly]