/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { GetBaseUrlRequestBuilderRequestsMetadata, type GetBaseUrlRequestBuilder } from './getBaseUrl/index.js';
// @ts-ignore
import { GetDeployListRequestBuilderRequestsMetadata, type GetDeployListRequestBuilder } from './getDeployList/index.js';
// @ts-ignore
import { GetEnvironmentServerListRequestBuilderRequestsMetadata, type GetEnvironmentServerListRequestBuilder } from './getEnvironmentServerList/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/Server
 */
export interface ServerRequestBuilder extends BaseRequestBuilder<ServerRequestBuilder> {
    /**
     * The GetBaseUrl property
     */
    get getBaseUrl(): GetBaseUrlRequestBuilder;
    /**
     * The GetDeployList property
     */
    get getDeployList(): GetDeployListRequestBuilder;
    /**
     * The GetEnvironmentServerList property
     */
    get getEnvironmentServerList(): GetEnvironmentServerListRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ServerRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/Server";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ServerRequestBuilderNavigationMetadata: Record<Exclude<keyof ServerRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    getBaseUrl: {
        requestsMetadata: GetBaseUrlRequestBuilderRequestsMetadata,
    },
    getDeployList: {
        requestsMetadata: GetDeployListRequestBuilderRequestsMetadata,
    },
    getEnvironmentServerList: {
        requestsMetadata: GetEnvironmentServerListRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
