/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorIRepositoryCodeAsync>d__11.MoveNext */

namespace MateralReleaseCenter.DeployServer.Abstractions.Repositories;
/// <summary>
/// 应用程序信息仓储
/// </summary>

public partial interface IApplicationInfoRepository : IDeployServerRepository<ApplicationInfo>

{
}
