/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorIRepositoryCodeAsync>d__11.MoveNext */

namespace MateralReleaseCenter.DeployServer.Abstractions.Repositories;
/// <summary>
/// 默认数据仓储
/// </summary>

public partial interface IDefaultDataRepository : IDeployServerRepository<DefaultData>

{
}
