/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorIRepositoryCodeAsync>d__11.MoveNext */

namespace MateralReleaseCenter.DeployServer.Abstractions.Repositories;
/// <summary>
/// 全局参数仓储
/// </summary>

public partial interface IGlobalParameterRepository : IDeployServerRepository<GlobalParameter>

{
}
