/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, type ResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/Stop
 */
export interface StopRequestBuilder extends BaseRequestBuilder<StopRequestBuilder> {
    /**
     * 停止程序
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     post(requestConfiguration?: RequestConfiguration<StopRequestBuilderPostQueryParameters> | undefined) : Promise<ResultModel | undefined>;
    /**
     * 停止程序
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<StopRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * 停止程序
 */
export interface StopRequestBuilderPostQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const StopRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/Stop{?id*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const StopRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: StopRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
