/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorIRepositoryCodeAsync>d__11.MoveNext */

namespace MateralReleaseCenter.ServerCenter.Abstractions.Repositories;
/// <summary>
/// 命名空间仓储
/// </summary>

public partial interface INamespaceRepository : IServerCenterRepository<Namespace>

{
}
