/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorIRepositoryCodeAsync>d__11.MoveNext */

namespace MateralReleaseCenter.ServerCenter.Abstractions.Repositories;
/// <summary>
/// 项目仓储
/// </summary>

public partial interface IProjectRepository : IServerCenterRepository<Project>

{
}
