/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorIRepositoryCodeAsync>d__11.MoveNext */

namespace MateralReleaseCenter.ServerCenter.Abstractions.Repositories;
/// <summary>
/// 用户仓储
/// </summary>

public partial interface IUserRepository : IServerCenterRepository<User>

{
}
