/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * 应用程序信息添加请求模型
 */
export interface AddApplicationInfoRequestModel extends Parsable {
    /**
     * 应用程序类型
     */
    applicationType?: number | null;
    /**
     * 增量更新
     */
    isIncrementalUpdating?: boolean | null;
    /**
     * 主模块
     */
    mainModule?: string | null;
    /**
     * 名称
     */
    name?: string | null;
    /**
     * 根路径
     */
    rootPath?: string | null;
    /**
     * 运行参数
     */
    runParams?: string | null;
}
/**
 * 默认数据添加请求模型
 */
export interface AddDefaultDataRequestModel extends Parsable {
    /**
     * 应用程序类型
     */
    applicationType?: number | null;
    /**
     * 数据
     */
    data?: string | null;
    /**
     * 键
     */
    key?: string | null;
}
/**
 * 应用程序信息数据传输模型
 */
export interface ApplicationInfoDTO extends Parsable {
    /**
     * 应用程序状态枚举
     */
    applicationStatus?: number | null;
    /**
     * 应用程序状文本
     */
    applicationStatusTxt?: string | null;
    /**
     * 应用程序类型
     */
    applicationType?: number | null;
    /**
     * 应用程序类型文本
     */
    applicationTypeTxt?: string | null;
    /**
     * 创建时间
     */
    createTime?: Date | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 增量更新
     */
    isIncrementalUpdating?: boolean | null;
    /**
     * 主模块
     */
    mainModule?: string | null;
    /**
     * 名称
     */
    name?: string | null;
    /**
     * 根路径
     */
    rootPath?: string | null;
    /**
     * 运行参数
     */
    runParams?: string | null;
    /**
     * 上传文件名称
     */
    uploadFileNames?: string[] | null;
}
export interface ApplicationInfoDTOResultModel extends Parsable {
    /**
     * 应用程序信息数据传输模型
     */
    data?: ApplicationInfoDTO | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * 应用程序信息列表数据传输模型
 */
export interface ApplicationInfoListDTO extends Parsable {
    /**
     * 应用程序状态枚举
     */
    applicationStatus?: number | null;
    /**
     * 应用程序状文本
     */
    applicationStatusTxt?: string | null;
    /**
     * 应用程序类型
     */
    applicationType?: number | null;
    /**
     * 应用程序类型文本
     */
    applicationTypeTxt?: string | null;
    /**
     * 创建时间
     */
    createTime?: Date | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 增量更新
     */
    isIncrementalUpdating?: boolean | null;
    /**
     * 主模块
     */
    mainModule?: string | null;
    /**
     * 名称
     */
    name?: string | null;
    /**
     * 根路径
     */
    rootPath?: string | null;
    /**
     * 运行参数
     */
    runParams?: string | null;
}
export interface ApplicationInfoListDTOCollectionResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: ApplicationInfoListDTO[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The PageModel property
     */
    pageModel?: PageModel | null;
    /**
     * The RangeModel property
     */
    rangeModel?: RangeModel | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
export interface ApplicationStatusEnumKeyValueModel extends Parsable {
    /**
     * 应用程序状态枚举
     */
    key?: number | null;
    /**
     * The Value property
     */
    value?: string | null;
}
export interface ApplicationStatusEnumKeyValueModelListResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: ApplicationStatusEnumKeyValueModel[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
export interface ApplicationTypeEnumKeyValueModel extends Parsable {
    /**
     * 应用程序类型
     */
    key?: number | null;
    /**
     * The Value property
     */
    value?: string | null;
}
export interface ApplicationTypeEnumKeyValueModelListResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: ApplicationTypeEnumKeyValueModel[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AddApplicationInfoRequestModel}
 */
// @ts-ignore
export function createAddApplicationInfoRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAddApplicationInfoRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AddDefaultDataRequestModel}
 */
// @ts-ignore
export function createAddDefaultDataRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAddDefaultDataRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ApplicationInfoDTO}
 */
// @ts-ignore
export function createApplicationInfoDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoApplicationInfoDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ApplicationInfoDTOResultModel}
 */
// @ts-ignore
export function createApplicationInfoDTOResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoApplicationInfoDTOResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ApplicationInfoListDTOCollectionResultModel}
 */
// @ts-ignore
export function createApplicationInfoListDTOCollectionResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoApplicationInfoListDTOCollectionResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ApplicationInfoListDTO}
 */
// @ts-ignore
export function createApplicationInfoListDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoApplicationInfoListDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ApplicationStatusEnumKeyValueModel}
 */
// @ts-ignore
export function createApplicationStatusEnumKeyValueModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoApplicationStatusEnumKeyValueModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ApplicationStatusEnumKeyValueModelListResultModel}
 */
// @ts-ignore
export function createApplicationStatusEnumKeyValueModelListResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoApplicationStatusEnumKeyValueModelListResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ApplicationTypeEnumKeyValueModel}
 */
// @ts-ignore
export function createApplicationTypeEnumKeyValueModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoApplicationTypeEnumKeyValueModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ApplicationTypeEnumKeyValueModelListResultModel}
 */
// @ts-ignore
export function createApplicationTypeEnumKeyValueModelListResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoApplicationTypeEnumKeyValueModelListResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DefaultDataDTO}
 */
// @ts-ignore
export function createDefaultDataDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDefaultDataDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DefaultDataDTOResultModel}
 */
// @ts-ignore
export function createDefaultDataDTOResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDefaultDataDTOResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DefaultDataListDTOCollectionResultModel}
 */
// @ts-ignore
export function createDefaultDataListDTOCollectionResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDefaultDataListDTOCollectionResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DefaultDataListDTO}
 */
// @ts-ignore
export function createDefaultDataListDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDefaultDataListDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EditApplicationInfoRequestModel}
 */
// @ts-ignore
export function createEditApplicationInfoRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEditApplicationInfoRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EditDefaultDataRequestModel}
 */
// @ts-ignore
export function createEditDefaultDataRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEditDefaultDataRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FileInfoDTO}
 */
// @ts-ignore
export function createFileInfoDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFileInfoDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FileInfoDTOListResultModel}
 */
// @ts-ignore
export function createFileInfoDTOListResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFileInfoDTOListResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GuidResultModel}
 */
// @ts-ignore
export function createGuidResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGuidResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Int32ResultModel}
 */
// @ts-ignore
export function createInt32ResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInt32ResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PageModel}
 */
// @ts-ignore
export function createPageModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPageModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryApplicationInfoRequestModel}
 */
// @ts-ignore
export function createQueryApplicationInfoRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryApplicationInfoRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryDefaultDataRequestModel}
 */
// @ts-ignore
export function createQueryDefaultDataRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryDefaultDataRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RangeModel}
 */
// @ts-ignore
export function createRangeModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRangeModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResultModel}
 */
// @ts-ignore
export function createResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResultTypeKeyValueModel}
 */
// @ts-ignore
export function createResultTypeKeyValueModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResultTypeKeyValueModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResultTypeKeyValueModelListResultModel}
 */
// @ts-ignore
export function createResultTypeKeyValueModelListResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResultTypeKeyValueModelListResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StringICollectionResultModel}
 */
// @ts-ignore
export function createStringICollectionResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStringICollectionResultModel;
}
/**
 * 默认数据数据传输模型
 */
export interface DefaultDataDTO extends Parsable {
    /**
     * 应用程序类型
     */
    applicationType?: number | null;
    /**
     * 应用程序类型文本
     */
    applicationTypeText?: string | null;
    /**
     * 创建时间
     */
    createTime?: Date | null;
    /**
     * 数据
     */
    data?: string | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 键
     */
    key?: string | null;
}
export interface DefaultDataDTOResultModel extends Parsable {
    /**
     * 默认数据数据传输模型
     */
    data?: DefaultDataDTO | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * 默认数据列表数据传输模型
 */
export interface DefaultDataListDTO extends Parsable {
    /**
     * 应用程序类型
     */
    applicationType?: number | null;
    /**
     * 应用程序类型文本
     */
    applicationTypeText?: string | null;
    /**
     * 创建时间
     */
    createTime?: Date | null;
    /**
     * 数据
     */
    data?: string | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 键
     */
    key?: string | null;
}
export interface DefaultDataListDTOCollectionResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: DefaultDataListDTO[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The PageModel property
     */
    pageModel?: PageModel | null;
    /**
     * The RangeModel property
     */
    rangeModel?: RangeModel | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * The deserialization information for the current model
 * @param AddApplicationInfoRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAddApplicationInfoRequestModel(addApplicationInfoRequestModel: Partial<AddApplicationInfoRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ApplicationType": n => { addApplicationInfoRequestModel.applicationType = n.getNumberValue(); },
        "IsIncrementalUpdating": n => { addApplicationInfoRequestModel.isIncrementalUpdating = n.getBooleanValue(); },
        "MainModule": n => { addApplicationInfoRequestModel.mainModule = n.getStringValue(); },
        "Name": n => { addApplicationInfoRequestModel.name = n.getStringValue(); },
        "RootPath": n => { addApplicationInfoRequestModel.rootPath = n.getStringValue(); },
        "RunParams": n => { addApplicationInfoRequestModel.runParams = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AddDefaultDataRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAddDefaultDataRequestModel(addDefaultDataRequestModel: Partial<AddDefaultDataRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ApplicationType": n => { addDefaultDataRequestModel.applicationType = n.getNumberValue(); },
        "Data": n => { addDefaultDataRequestModel.data = n.getStringValue(); },
        "Key": n => { addDefaultDataRequestModel.key = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ApplicationInfoDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoApplicationInfoDTO(applicationInfoDTO: Partial<ApplicationInfoDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ApplicationStatus": n => { applicationInfoDTO.applicationStatus = n.getNumberValue(); },
        "ApplicationStatusTxt": n => { applicationInfoDTO.applicationStatusTxt = n.getStringValue(); },
        "ApplicationType": n => { applicationInfoDTO.applicationType = n.getNumberValue(); },
        "ApplicationTypeTxt": n => { applicationInfoDTO.applicationTypeTxt = n.getStringValue(); },
        "CreateTime": n => { applicationInfoDTO.createTime = n.getDateValue(); },
        "ID": n => { applicationInfoDTO.iD = n.getGuidValue(); },
        "IsIncrementalUpdating": n => { applicationInfoDTO.isIncrementalUpdating = n.getBooleanValue(); },
        "MainModule": n => { applicationInfoDTO.mainModule = n.getStringValue(); },
        "Name": n => { applicationInfoDTO.name = n.getStringValue(); },
        "RootPath": n => { applicationInfoDTO.rootPath = n.getStringValue(); },
        "RunParams": n => { applicationInfoDTO.runParams = n.getStringValue(); },
        "UploadFileNames": n => { applicationInfoDTO.uploadFileNames = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ApplicationInfoDTOResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoApplicationInfoDTOResultModel(applicationInfoDTOResultModel: Partial<ApplicationInfoDTOResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { applicationInfoDTOResultModel.data = n.getObjectValue<ApplicationInfoDTO>(createApplicationInfoDTOFromDiscriminatorValue); },
        "Message": n => { applicationInfoDTOResultModel.message = n.getStringValue(); },
        "ResultType": n => { applicationInfoDTOResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ApplicationInfoListDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoApplicationInfoListDTO(applicationInfoListDTO: Partial<ApplicationInfoListDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ApplicationStatus": n => { applicationInfoListDTO.applicationStatus = n.getNumberValue(); },
        "ApplicationStatusTxt": n => { applicationInfoListDTO.applicationStatusTxt = n.getStringValue(); },
        "ApplicationType": n => { applicationInfoListDTO.applicationType = n.getNumberValue(); },
        "ApplicationTypeTxt": n => { applicationInfoListDTO.applicationTypeTxt = n.getStringValue(); },
        "CreateTime": n => { applicationInfoListDTO.createTime = n.getDateValue(); },
        "ID": n => { applicationInfoListDTO.iD = n.getGuidValue(); },
        "IsIncrementalUpdating": n => { applicationInfoListDTO.isIncrementalUpdating = n.getBooleanValue(); },
        "MainModule": n => { applicationInfoListDTO.mainModule = n.getStringValue(); },
        "Name": n => { applicationInfoListDTO.name = n.getStringValue(); },
        "RootPath": n => { applicationInfoListDTO.rootPath = n.getStringValue(); },
        "RunParams": n => { applicationInfoListDTO.runParams = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ApplicationInfoListDTOCollectionResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoApplicationInfoListDTOCollectionResultModel(applicationInfoListDTOCollectionResultModel: Partial<ApplicationInfoListDTOCollectionResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { applicationInfoListDTOCollectionResultModel.data = n.getCollectionOfObjectValues<ApplicationInfoListDTO>(createApplicationInfoListDTOFromDiscriminatorValue); },
        "Message": n => { applicationInfoListDTOCollectionResultModel.message = n.getStringValue(); },
        "PageModel": n => { applicationInfoListDTOCollectionResultModel.pageModel = n.getObjectValue<PageModel>(createPageModelFromDiscriminatorValue); },
        "RangeModel": n => { applicationInfoListDTOCollectionResultModel.rangeModel = n.getObjectValue<RangeModel>(createRangeModelFromDiscriminatorValue); },
        "ResultType": n => { applicationInfoListDTOCollectionResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ApplicationStatusEnumKeyValueModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoApplicationStatusEnumKeyValueModel(applicationStatusEnumKeyValueModel: Partial<ApplicationStatusEnumKeyValueModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Key": n => { applicationStatusEnumKeyValueModel.key = n.getNumberValue(); },
        "Value": n => { applicationStatusEnumKeyValueModel.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ApplicationStatusEnumKeyValueModelListResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoApplicationStatusEnumKeyValueModelListResultModel(applicationStatusEnumKeyValueModelListResultModel: Partial<ApplicationStatusEnumKeyValueModelListResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { applicationStatusEnumKeyValueModelListResultModel.data = n.getCollectionOfObjectValues<ApplicationStatusEnumKeyValueModel>(createApplicationStatusEnumKeyValueModelFromDiscriminatorValue); },
        "Message": n => { applicationStatusEnumKeyValueModelListResultModel.message = n.getStringValue(); },
        "ResultType": n => { applicationStatusEnumKeyValueModelListResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ApplicationTypeEnumKeyValueModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoApplicationTypeEnumKeyValueModel(applicationTypeEnumKeyValueModel: Partial<ApplicationTypeEnumKeyValueModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Key": n => { applicationTypeEnumKeyValueModel.key = n.getNumberValue(); },
        "Value": n => { applicationTypeEnumKeyValueModel.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ApplicationTypeEnumKeyValueModelListResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoApplicationTypeEnumKeyValueModelListResultModel(applicationTypeEnumKeyValueModelListResultModel: Partial<ApplicationTypeEnumKeyValueModelListResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { applicationTypeEnumKeyValueModelListResultModel.data = n.getCollectionOfObjectValues<ApplicationTypeEnumKeyValueModel>(createApplicationTypeEnumKeyValueModelFromDiscriminatorValue); },
        "Message": n => { applicationTypeEnumKeyValueModelListResultModel.message = n.getStringValue(); },
        "ResultType": n => { applicationTypeEnumKeyValueModelListResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DefaultDataDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDefaultDataDTO(defaultDataDTO: Partial<DefaultDataDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ApplicationType": n => { defaultDataDTO.applicationType = n.getNumberValue(); },
        "ApplicationTypeText": n => { defaultDataDTO.applicationTypeText = n.getStringValue(); },
        "CreateTime": n => { defaultDataDTO.createTime = n.getDateValue(); },
        "Data": n => { defaultDataDTO.data = n.getStringValue(); },
        "ID": n => { defaultDataDTO.iD = n.getGuidValue(); },
        "Key": n => { defaultDataDTO.key = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DefaultDataDTOResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDefaultDataDTOResultModel(defaultDataDTOResultModel: Partial<DefaultDataDTOResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { defaultDataDTOResultModel.data = n.getObjectValue<DefaultDataDTO>(createDefaultDataDTOFromDiscriminatorValue); },
        "Message": n => { defaultDataDTOResultModel.message = n.getStringValue(); },
        "ResultType": n => { defaultDataDTOResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DefaultDataListDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDefaultDataListDTO(defaultDataListDTO: Partial<DefaultDataListDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ApplicationType": n => { defaultDataListDTO.applicationType = n.getNumberValue(); },
        "ApplicationTypeText": n => { defaultDataListDTO.applicationTypeText = n.getStringValue(); },
        "CreateTime": n => { defaultDataListDTO.createTime = n.getDateValue(); },
        "Data": n => { defaultDataListDTO.data = n.getStringValue(); },
        "ID": n => { defaultDataListDTO.iD = n.getGuidValue(); },
        "Key": n => { defaultDataListDTO.key = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DefaultDataListDTOCollectionResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDefaultDataListDTOCollectionResultModel(defaultDataListDTOCollectionResultModel: Partial<DefaultDataListDTOCollectionResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { defaultDataListDTOCollectionResultModel.data = n.getCollectionOfObjectValues<DefaultDataListDTO>(createDefaultDataListDTOFromDiscriminatorValue); },
        "Message": n => { defaultDataListDTOCollectionResultModel.message = n.getStringValue(); },
        "PageModel": n => { defaultDataListDTOCollectionResultModel.pageModel = n.getObjectValue<PageModel>(createPageModelFromDiscriminatorValue); },
        "RangeModel": n => { defaultDataListDTOCollectionResultModel.rangeModel = n.getObjectValue<RangeModel>(createRangeModelFromDiscriminatorValue); },
        "ResultType": n => { defaultDataListDTOCollectionResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EditApplicationInfoRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEditApplicationInfoRequestModel(editApplicationInfoRequestModel: Partial<EditApplicationInfoRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ApplicationType": n => { editApplicationInfoRequestModel.applicationType = n.getNumberValue(); },
        "ID": n => { editApplicationInfoRequestModel.iD = n.getGuidValue(); },
        "IsIncrementalUpdating": n => { editApplicationInfoRequestModel.isIncrementalUpdating = n.getBooleanValue(); },
        "MainModule": n => { editApplicationInfoRequestModel.mainModule = n.getStringValue(); },
        "RunParams": n => { editApplicationInfoRequestModel.runParams = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EditDefaultDataRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEditDefaultDataRequestModel(editDefaultDataRequestModel: Partial<EditDefaultDataRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ApplicationType": n => { editDefaultDataRequestModel.applicationType = n.getNumberValue(); },
        "Data": n => { editDefaultDataRequestModel.data = n.getStringValue(); },
        "ID": n => { editDefaultDataRequestModel.iD = n.getGuidValue(); },
        "Key": n => { editDefaultDataRequestModel.key = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param FileInfoDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFileInfoDTO(fileInfoDTO: Partial<FileInfoDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "DownloadUrl": n => { fileInfoDTO.downloadUrl = n.getStringValue(); },
        "LastWriteTime": n => { fileInfoDTO.lastWriteTime = n.getDateValue(); },
        "Name": n => { fileInfoDTO.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param FileInfoDTOListResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFileInfoDTOListResultModel(fileInfoDTOListResultModel: Partial<FileInfoDTOListResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { fileInfoDTOListResultModel.data = n.getCollectionOfObjectValues<FileInfoDTO>(createFileInfoDTOFromDiscriminatorValue); },
        "Message": n => { fileInfoDTOListResultModel.message = n.getStringValue(); },
        "ResultType": n => { fileInfoDTOListResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param GuidResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGuidResultModel(guidResultModel: Partial<GuidResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { guidResultModel.data = n.getGuidValue(); },
        "Message": n => { guidResultModel.message = n.getStringValue(); },
        "ResultType": n => { guidResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Int32ResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInt32ResultModel(int32ResultModel: Partial<Int32ResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { int32ResultModel.data = n.getNumberValue(); },
        "Message": n => { int32ResultModel.message = n.getStringValue(); },
        "ResultType": n => { int32ResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PageModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPageModel(pageModel: Partial<PageModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "DataCount": n => { pageModel.dataCount = n.getNumberValue(); },
        "IsAsc": n => { pageModel.isAsc = n.getBooleanValue(); },
        "PageCount": n => { pageModel.pageCount = n.getNumberValue(); },
        "PageIndex": n => { pageModel.pageIndex = n.getNumberValue(); },
        "PageSize": n => { pageModel.pageSize = n.getNumberValue(); },
        "Skip": n => { pageModel.skip = n.getNumberValue(); },
        "SortPropertyName": n => { pageModel.sortPropertyName = n.getStringValue(); },
        "StartIndex": n => { pageModel.startIndex = n.getNumberValue(); },
        "Take": n => { pageModel.take = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QueryApplicationInfoRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryApplicationInfoRequestModel(queryApplicationInfoRequestModel: Partial<QueryApplicationInfoRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ApplicationStatus": n => { queryApplicationInfoRequestModel.applicationStatus = n.getNumberValue(); },
        "ApplicationType": n => { queryApplicationInfoRequestModel.applicationType = n.getNumberValue(); },
        "IDs": n => { queryApplicationInfoRequestModel.iDs = n.getCollectionOfPrimitiveValues<Guid>(); },
        "IsAsc": n => { queryApplicationInfoRequestModel.isAsc = n.getBooleanValue(); },
        "IsIncrementalUpdating": n => { queryApplicationInfoRequestModel.isIncrementalUpdating = n.getBooleanValue(); },
        "MainModule": n => { queryApplicationInfoRequestModel.mainModule = n.getStringValue(); },
        "MaxCreateTime": n => { queryApplicationInfoRequestModel.maxCreateTime = n.getDateValue(); },
        "MinCreateTime": n => { queryApplicationInfoRequestModel.minCreateTime = n.getDateValue(); },
        "Name": n => { queryApplicationInfoRequestModel.name = n.getStringValue(); },
        "PageIndex": n => { queryApplicationInfoRequestModel.pageIndex = n.getNumberValue(); },
        "PageSize": n => { queryApplicationInfoRequestModel.pageSize = n.getNumberValue(); },
        "RootPath": n => { queryApplicationInfoRequestModel.rootPath = n.getStringValue(); },
        "Skip": n => { queryApplicationInfoRequestModel.skip = n.getNumberValue(); },
        "SortPropertyName": n => { queryApplicationInfoRequestModel.sortPropertyName = n.getStringValue(); },
        "Take": n => { queryApplicationInfoRequestModel.take = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QueryDefaultDataRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryDefaultDataRequestModel(queryDefaultDataRequestModel: Partial<QueryDefaultDataRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ApplicationType": n => { queryDefaultDataRequestModel.applicationType = n.getNumberValue(); },
        "IDs": n => { queryDefaultDataRequestModel.iDs = n.getCollectionOfPrimitiveValues<Guid>(); },
        "IsAsc": n => { queryDefaultDataRequestModel.isAsc = n.getBooleanValue(); },
        "Key": n => { queryDefaultDataRequestModel.key = n.getStringValue(); },
        "MaxCreateTime": n => { queryDefaultDataRequestModel.maxCreateTime = n.getDateValue(); },
        "MinCreateTime": n => { queryDefaultDataRequestModel.minCreateTime = n.getDateValue(); },
        "PageIndex": n => { queryDefaultDataRequestModel.pageIndex = n.getNumberValue(); },
        "PageSize": n => { queryDefaultDataRequestModel.pageSize = n.getNumberValue(); },
        "Skip": n => { queryDefaultDataRequestModel.skip = n.getNumberValue(); },
        "SortPropertyName": n => { queryDefaultDataRequestModel.sortPropertyName = n.getStringValue(); },
        "Take": n => { queryDefaultDataRequestModel.take = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RangeModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRangeModel(rangeModel: Partial<RangeModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "DataCount": n => { rangeModel.dataCount = n.getNumberValue(); },
        "IsAsc": n => { rangeModel.isAsc = n.getBooleanValue(); },
        "Skip": n => { rangeModel.skip = n.getNumberValue(); },
        "SortPropertyName": n => { rangeModel.sortPropertyName = n.getStringValue(); },
        "Take": n => { rangeModel.take = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResultModel(resultModel: Partial<ResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Message": n => { resultModel.message = n.getStringValue(); },
        "ResultType": n => { resultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ResultTypeKeyValueModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResultTypeKeyValueModel(resultTypeKeyValueModel: Partial<ResultTypeKeyValueModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Key": n => { resultTypeKeyValueModel.key = n.getNumberValue(); },
        "Value": n => { resultTypeKeyValueModel.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ResultTypeKeyValueModelListResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResultTypeKeyValueModelListResultModel(resultTypeKeyValueModelListResultModel: Partial<ResultTypeKeyValueModelListResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { resultTypeKeyValueModelListResultModel.data = n.getCollectionOfObjectValues<ResultTypeKeyValueModel>(createResultTypeKeyValueModelFromDiscriminatorValue); },
        "Message": n => { resultTypeKeyValueModelListResultModel.message = n.getStringValue(); },
        "ResultType": n => { resultTypeKeyValueModelListResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param StringICollectionResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStringICollectionResultModel(stringICollectionResultModel: Partial<StringICollectionResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { stringICollectionResultModel.data = n.getCollectionOfPrimitiveValues<string>(); },
        "Message": n => { stringICollectionResultModel.message = n.getStringValue(); },
        "ResultType": n => { stringICollectionResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * 应用程序信息修改请求模型
 */
export interface EditApplicationInfoRequestModel extends Parsable {
    /**
     * 应用程序类型
     */
    applicationType?: number | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 增量更新
     */
    isIncrementalUpdating?: boolean | null;
    /**
     * 主模块
     */
    mainModule?: string | null;
    /**
     * 运行参数
     */
    runParams?: string | null;
}
/**
 * 默认数据修改请求模型
 */
export interface EditDefaultDataRequestModel extends Parsable {
    /**
     * 应用程序类型
     */
    applicationType?: number | null;
    /**
     * 数据
     */
    data?: string | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 键
     */
    key?: string | null;
}
/**
 * 文件信息数据传输模型
 */
export interface FileInfoDTO extends Parsable {
    /**
     * 下载地址
     */
    downloadUrl?: string | null;
    /**
     * 最后写入时间
     */
    lastWriteTime?: Date | null;
    /**
     * 名称
     */
    name?: string | null;
}
export interface FileInfoDTOListResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: FileInfoDTO[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
export interface GuidResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: Guid | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
export interface Int32ResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: number | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
export interface PageModel extends Parsable {
    /**
     * The DataCount property
     */
    dataCount?: number | null;
    /**
     * The IsAsc property
     */
    isAsc?: boolean | null;
    /**
     * The PageCount property
     */
    pageCount?: number | null;
    /**
     * The PageIndex property
     */
    pageIndex?: number | null;
    /**
     * The PageSize property
     */
    pageSize?: number | null;
    /**
     * The Skip property
     */
    skip?: number | null;
    /**
     * The SortPropertyName property
     */
    sortPropertyName?: string | null;
    /**
     * The StartIndex property
     */
    startIndex?: number | null;
    /**
     * The Take property
     */
    take?: number | null;
}
/**
 * 应用程序信息查询请求模型
 */
export interface QueryApplicationInfoRequestModel extends Parsable {
    /**
     * 应用程序状态枚举
     */
    applicationStatus?: number | null;
    /**
     * 应用程序类型
     */
    applicationType?: number | null;
    /**
     * 唯一标识组
     */
    iDs?: Guid[] | null;
    /**
     * The IsAsc property
     */
    isAsc?: boolean | null;
    /**
     * 增量更新
     */
    isIncrementalUpdating?: boolean | null;
    /**
     * 主模块
     */
    mainModule?: string | null;
    /**
     * 最大创建时间
     */
    maxCreateTime?: Date | null;
    /**
     * 最小创建时间
     */
    minCreateTime?: Date | null;
    /**
     * 名称
     */
    name?: string | null;
    /**
     * The PageIndex property
     */
    pageIndex?: number | null;
    /**
     * The PageSize property
     */
    pageSize?: number | null;
    /**
     * 根路径
     */
    rootPath?: string | null;
    /**
     * The Skip property
     */
    skip?: number | null;
    /**
     * The SortPropertyName property
     */
    sortPropertyName?: string | null;
    /**
     * The Take property
     */
    take?: number | null;
}
/**
 * 默认数据查询请求模型
 */
export interface QueryDefaultDataRequestModel extends Parsable {
    /**
     * 应用程序类型
     */
    applicationType?: number | null;
    /**
     * 唯一标识组
     */
    iDs?: Guid[] | null;
    /**
     * The IsAsc property
     */
    isAsc?: boolean | null;
    /**
     * 键
     */
    key?: string | null;
    /**
     * 最大创建时间
     */
    maxCreateTime?: Date | null;
    /**
     * 最小创建时间
     */
    minCreateTime?: Date | null;
    /**
     * The PageIndex property
     */
    pageIndex?: number | null;
    /**
     * The PageSize property
     */
    pageSize?: number | null;
    /**
     * The Skip property
     */
    skip?: number | null;
    /**
     * The SortPropertyName property
     */
    sortPropertyName?: string | null;
    /**
     * The Take property
     */
    take?: number | null;
}
export interface RangeModel extends Parsable {
    /**
     * The DataCount property
     */
    dataCount?: number | null;
    /**
     * The IsAsc property
     */
    isAsc?: boolean | null;
    /**
     * The Skip property
     */
    skip?: number | null;
    /**
     * The SortPropertyName property
     */
    sortPropertyName?: string | null;
    /**
     * The Take property
     */
    take?: number | null;
}
export interface ResultModel extends Parsable {
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
export interface ResultTypeKeyValueModel extends Parsable {
    /**
     * The Key property
     */
    key?: number | null;
    /**
     * The Value property
     */
    value?: string | null;
}
export interface ResultTypeKeyValueModelListResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: ResultTypeKeyValueModel[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * Serializes information the current object
 * @param AddApplicationInfoRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAddApplicationInfoRequestModel(writer: SerializationWriter, addApplicationInfoRequestModel: Partial<AddApplicationInfoRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!addApplicationInfoRequestModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("ApplicationType", addApplicationInfoRequestModel.applicationType);
    writer.writeBooleanValue("IsIncrementalUpdating", addApplicationInfoRequestModel.isIncrementalUpdating);
    writer.writeStringValue("MainModule", addApplicationInfoRequestModel.mainModule);
    writer.writeStringValue("Name", addApplicationInfoRequestModel.name);
    writer.writeStringValue("RootPath", addApplicationInfoRequestModel.rootPath);
    writer.writeStringValue("RunParams", addApplicationInfoRequestModel.runParams);
}
/**
 * Serializes information the current object
 * @param AddDefaultDataRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAddDefaultDataRequestModel(writer: SerializationWriter, addDefaultDataRequestModel: Partial<AddDefaultDataRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!addDefaultDataRequestModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("ApplicationType", addDefaultDataRequestModel.applicationType);
    writer.writeStringValue("Data", addDefaultDataRequestModel.data);
    writer.writeStringValue("Key", addDefaultDataRequestModel.key);
}
/**
 * Serializes information the current object
 * @param ApplicationInfoDTO The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeApplicationInfoDTO(writer: SerializationWriter, applicationInfoDTO: Partial<ApplicationInfoDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!applicationInfoDTO || isSerializingDerivedType) { return; }
    writer.writeNumberValue("ApplicationStatus", applicationInfoDTO.applicationStatus);
    writer.writeNumberValue("ApplicationType", applicationInfoDTO.applicationType);
    writer.writeDateValue("CreateTime", applicationInfoDTO.createTime);
    writer.writeGuidValue("ID", applicationInfoDTO.iD);
    writer.writeBooleanValue("IsIncrementalUpdating", applicationInfoDTO.isIncrementalUpdating);
    writer.writeStringValue("MainModule", applicationInfoDTO.mainModule);
    writer.writeStringValue("Name", applicationInfoDTO.name);
    writer.writeStringValue("RootPath", applicationInfoDTO.rootPath);
    writer.writeStringValue("RunParams", applicationInfoDTO.runParams);
    writer.writeCollectionOfPrimitiveValues<string>("UploadFileNames", applicationInfoDTO.uploadFileNames);
}
/**
 * Serializes information the current object
 * @param ApplicationInfoDTOResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeApplicationInfoDTOResultModel(writer: SerializationWriter, applicationInfoDTOResultModel: Partial<ApplicationInfoDTOResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!applicationInfoDTOResultModel || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ApplicationInfoDTO>("Data", applicationInfoDTOResultModel.data, serializeApplicationInfoDTO);
    writer.writeStringValue("Message", applicationInfoDTOResultModel.message);
    writer.writeNumberValue("ResultType", applicationInfoDTOResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param ApplicationInfoListDTO The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeApplicationInfoListDTO(writer: SerializationWriter, applicationInfoListDTO: Partial<ApplicationInfoListDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!applicationInfoListDTO || isSerializingDerivedType) { return; }
    writer.writeNumberValue("ApplicationStatus", applicationInfoListDTO.applicationStatus);
    writer.writeNumberValue("ApplicationType", applicationInfoListDTO.applicationType);
    writer.writeDateValue("CreateTime", applicationInfoListDTO.createTime);
    writer.writeGuidValue("ID", applicationInfoListDTO.iD);
    writer.writeBooleanValue("IsIncrementalUpdating", applicationInfoListDTO.isIncrementalUpdating);
    writer.writeStringValue("MainModule", applicationInfoListDTO.mainModule);
    writer.writeStringValue("Name", applicationInfoListDTO.name);
    writer.writeStringValue("RootPath", applicationInfoListDTO.rootPath);
    writer.writeStringValue("RunParams", applicationInfoListDTO.runParams);
}
/**
 * Serializes information the current object
 * @param ApplicationInfoListDTOCollectionResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeApplicationInfoListDTOCollectionResultModel(writer: SerializationWriter, applicationInfoListDTOCollectionResultModel: Partial<ApplicationInfoListDTOCollectionResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!applicationInfoListDTOCollectionResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ApplicationInfoListDTO>("Data", applicationInfoListDTOCollectionResultModel.data, serializeApplicationInfoListDTO);
    writer.writeStringValue("Message", applicationInfoListDTOCollectionResultModel.message);
    writer.writeObjectValue<PageModel>("PageModel", applicationInfoListDTOCollectionResultModel.pageModel, serializePageModel);
    writer.writeObjectValue<RangeModel>("RangeModel", applicationInfoListDTOCollectionResultModel.rangeModel, serializeRangeModel);
    writer.writeNumberValue("ResultType", applicationInfoListDTOCollectionResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param ApplicationStatusEnumKeyValueModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeApplicationStatusEnumKeyValueModel(writer: SerializationWriter, applicationStatusEnumKeyValueModel: Partial<ApplicationStatusEnumKeyValueModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!applicationStatusEnumKeyValueModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("Key", applicationStatusEnumKeyValueModel.key);
}
/**
 * Serializes information the current object
 * @param ApplicationStatusEnumKeyValueModelListResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeApplicationStatusEnumKeyValueModelListResultModel(writer: SerializationWriter, applicationStatusEnumKeyValueModelListResultModel: Partial<ApplicationStatusEnumKeyValueModelListResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!applicationStatusEnumKeyValueModelListResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ApplicationStatusEnumKeyValueModel>("Data", applicationStatusEnumKeyValueModelListResultModel.data, serializeApplicationStatusEnumKeyValueModel);
    writer.writeStringValue("Message", applicationStatusEnumKeyValueModelListResultModel.message);
    writer.writeNumberValue("ResultType", applicationStatusEnumKeyValueModelListResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param ApplicationTypeEnumKeyValueModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeApplicationTypeEnumKeyValueModel(writer: SerializationWriter, applicationTypeEnumKeyValueModel: Partial<ApplicationTypeEnumKeyValueModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!applicationTypeEnumKeyValueModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("Key", applicationTypeEnumKeyValueModel.key);
}
/**
 * Serializes information the current object
 * @param ApplicationTypeEnumKeyValueModelListResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeApplicationTypeEnumKeyValueModelListResultModel(writer: SerializationWriter, applicationTypeEnumKeyValueModelListResultModel: Partial<ApplicationTypeEnumKeyValueModelListResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!applicationTypeEnumKeyValueModelListResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ApplicationTypeEnumKeyValueModel>("Data", applicationTypeEnumKeyValueModelListResultModel.data, serializeApplicationTypeEnumKeyValueModel);
    writer.writeStringValue("Message", applicationTypeEnumKeyValueModelListResultModel.message);
    writer.writeNumberValue("ResultType", applicationTypeEnumKeyValueModelListResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param DefaultDataDTO The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDefaultDataDTO(writer: SerializationWriter, defaultDataDTO: Partial<DefaultDataDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!defaultDataDTO || isSerializingDerivedType) { return; }
    writer.writeNumberValue("ApplicationType", defaultDataDTO.applicationType);
    writer.writeDateValue("CreateTime", defaultDataDTO.createTime);
    writer.writeStringValue("Data", defaultDataDTO.data);
    writer.writeGuidValue("ID", defaultDataDTO.iD);
    writer.writeStringValue("Key", defaultDataDTO.key);
}
/**
 * Serializes information the current object
 * @param DefaultDataDTOResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDefaultDataDTOResultModel(writer: SerializationWriter, defaultDataDTOResultModel: Partial<DefaultDataDTOResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!defaultDataDTOResultModel || isSerializingDerivedType) { return; }
    writer.writeObjectValue<DefaultDataDTO>("Data", defaultDataDTOResultModel.data, serializeDefaultDataDTO);
    writer.writeStringValue("Message", defaultDataDTOResultModel.message);
    writer.writeNumberValue("ResultType", defaultDataDTOResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param DefaultDataListDTO The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDefaultDataListDTO(writer: SerializationWriter, defaultDataListDTO: Partial<DefaultDataListDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!defaultDataListDTO || isSerializingDerivedType) { return; }
    writer.writeNumberValue("ApplicationType", defaultDataListDTO.applicationType);
    writer.writeDateValue("CreateTime", defaultDataListDTO.createTime);
    writer.writeStringValue("Data", defaultDataListDTO.data);
    writer.writeGuidValue("ID", defaultDataListDTO.iD);
    writer.writeStringValue("Key", defaultDataListDTO.key);
}
/**
 * Serializes information the current object
 * @param DefaultDataListDTOCollectionResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDefaultDataListDTOCollectionResultModel(writer: SerializationWriter, defaultDataListDTOCollectionResultModel: Partial<DefaultDataListDTOCollectionResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!defaultDataListDTOCollectionResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<DefaultDataListDTO>("Data", defaultDataListDTOCollectionResultModel.data, serializeDefaultDataListDTO);
    writer.writeStringValue("Message", defaultDataListDTOCollectionResultModel.message);
    writer.writeObjectValue<PageModel>("PageModel", defaultDataListDTOCollectionResultModel.pageModel, serializePageModel);
    writer.writeObjectValue<RangeModel>("RangeModel", defaultDataListDTOCollectionResultModel.rangeModel, serializeRangeModel);
    writer.writeNumberValue("ResultType", defaultDataListDTOCollectionResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param EditApplicationInfoRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEditApplicationInfoRequestModel(writer: SerializationWriter, editApplicationInfoRequestModel: Partial<EditApplicationInfoRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!editApplicationInfoRequestModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("ApplicationType", editApplicationInfoRequestModel.applicationType);
    writer.writeGuidValue("ID", editApplicationInfoRequestModel.iD);
    writer.writeBooleanValue("IsIncrementalUpdating", editApplicationInfoRequestModel.isIncrementalUpdating);
    writer.writeStringValue("MainModule", editApplicationInfoRequestModel.mainModule);
    writer.writeStringValue("RunParams", editApplicationInfoRequestModel.runParams);
}
/**
 * Serializes information the current object
 * @param EditDefaultDataRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEditDefaultDataRequestModel(writer: SerializationWriter, editDefaultDataRequestModel: Partial<EditDefaultDataRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!editDefaultDataRequestModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("ApplicationType", editDefaultDataRequestModel.applicationType);
    writer.writeStringValue("Data", editDefaultDataRequestModel.data);
    writer.writeGuidValue("ID", editDefaultDataRequestModel.iD);
    writer.writeStringValue("Key", editDefaultDataRequestModel.key);
}
/**
 * Serializes information the current object
 * @param FileInfoDTO The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFileInfoDTO(writer: SerializationWriter, fileInfoDTO: Partial<FileInfoDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!fileInfoDTO || isSerializingDerivedType) { return; }
    writer.writeStringValue("DownloadUrl", fileInfoDTO.downloadUrl);
    writer.writeDateValue("LastWriteTime", fileInfoDTO.lastWriteTime);
    writer.writeStringValue("Name", fileInfoDTO.name);
}
/**
 * Serializes information the current object
 * @param FileInfoDTOListResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFileInfoDTOListResultModel(writer: SerializationWriter, fileInfoDTOListResultModel: Partial<FileInfoDTOListResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!fileInfoDTOListResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<FileInfoDTO>("Data", fileInfoDTOListResultModel.data, serializeFileInfoDTO);
    writer.writeStringValue("Message", fileInfoDTOListResultModel.message);
    writer.writeNumberValue("ResultType", fileInfoDTOListResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param GuidResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGuidResultModel(writer: SerializationWriter, guidResultModel: Partial<GuidResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!guidResultModel || isSerializingDerivedType) { return; }
    writer.writeGuidValue("Data", guidResultModel.data);
    writer.writeStringValue("Message", guidResultModel.message);
    writer.writeNumberValue("ResultType", guidResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param Int32ResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInt32ResultModel(writer: SerializationWriter, int32ResultModel: Partial<Int32ResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!int32ResultModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("Data", int32ResultModel.data);
    writer.writeStringValue("Message", int32ResultModel.message);
    writer.writeNumberValue("ResultType", int32ResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PageModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePageModel(writer: SerializationWriter, pageModel: Partial<PageModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pageModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("DataCount", pageModel.dataCount);
    writer.writeBooleanValue("IsAsc", pageModel.isAsc);
    writer.writeNumberValue("PageIndex", pageModel.pageIndex);
    writer.writeNumberValue("PageSize", pageModel.pageSize);
    writer.writeNumberValue("Skip", pageModel.skip);
    writer.writeStringValue("SortPropertyName", pageModel.sortPropertyName);
    writer.writeNumberValue("Take", pageModel.take);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QueryApplicationInfoRequestModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryApplicationInfoRequestModel(writer: SerializationWriter, queryApplicationInfoRequestModel: Partial<QueryApplicationInfoRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!queryApplicationInfoRequestModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("ApplicationStatus", queryApplicationInfoRequestModel.applicationStatus);
    writer.writeNumberValue("ApplicationType", queryApplicationInfoRequestModel.applicationType);
    writer.writeCollectionOfPrimitiveValues<Guid>("IDs", queryApplicationInfoRequestModel.iDs);
    writer.writeBooleanValue("IsAsc", queryApplicationInfoRequestModel.isAsc);
    writer.writeBooleanValue("IsIncrementalUpdating", queryApplicationInfoRequestModel.isIncrementalUpdating);
    writer.writeStringValue("MainModule", queryApplicationInfoRequestModel.mainModule);
    writer.writeDateValue("MaxCreateTime", queryApplicationInfoRequestModel.maxCreateTime);
    writer.writeDateValue("MinCreateTime", queryApplicationInfoRequestModel.minCreateTime);
    writer.writeStringValue("Name", queryApplicationInfoRequestModel.name);
    writer.writeNumberValue("PageIndex", queryApplicationInfoRequestModel.pageIndex);
    writer.writeNumberValue("PageSize", queryApplicationInfoRequestModel.pageSize);
    writer.writeStringValue("RootPath", queryApplicationInfoRequestModel.rootPath);
    writer.writeNumberValue("Skip", queryApplicationInfoRequestModel.skip);
    writer.writeStringValue("SortPropertyName", queryApplicationInfoRequestModel.sortPropertyName);
    writer.writeNumberValue("Take", queryApplicationInfoRequestModel.take);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QueryDefaultDataRequestModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryDefaultDataRequestModel(writer: SerializationWriter, queryDefaultDataRequestModel: Partial<QueryDefaultDataRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!queryDefaultDataRequestModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("ApplicationType", queryDefaultDataRequestModel.applicationType);
    writer.writeCollectionOfPrimitiveValues<Guid>("IDs", queryDefaultDataRequestModel.iDs);
    writer.writeBooleanValue("IsAsc", queryDefaultDataRequestModel.isAsc);
    writer.writeStringValue("Key", queryDefaultDataRequestModel.key);
    writer.writeDateValue("MaxCreateTime", queryDefaultDataRequestModel.maxCreateTime);
    writer.writeDateValue("MinCreateTime", queryDefaultDataRequestModel.minCreateTime);
    writer.writeNumberValue("PageIndex", queryDefaultDataRequestModel.pageIndex);
    writer.writeNumberValue("PageSize", queryDefaultDataRequestModel.pageSize);
    writer.writeNumberValue("Skip", queryDefaultDataRequestModel.skip);
    writer.writeStringValue("SortPropertyName", queryDefaultDataRequestModel.sortPropertyName);
    writer.writeNumberValue("Take", queryDefaultDataRequestModel.take);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RangeModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRangeModel(writer: SerializationWriter, rangeModel: Partial<RangeModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!rangeModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("DataCount", rangeModel.dataCount);
    writer.writeBooleanValue("IsAsc", rangeModel.isAsc);
    writer.writeNumberValue("Skip", rangeModel.skip);
    writer.writeStringValue("SortPropertyName", rangeModel.sortPropertyName);
    writer.writeNumberValue("Take", rangeModel.take);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResultModel(writer: SerializationWriter, resultModel: Partial<ResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!resultModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Message", resultModel.message);
    writer.writeNumberValue("ResultType", resultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResultTypeKeyValueModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResultTypeKeyValueModel(writer: SerializationWriter, resultTypeKeyValueModel: Partial<ResultTypeKeyValueModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!resultTypeKeyValueModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("Key", resultTypeKeyValueModel.key);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResultTypeKeyValueModelListResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResultTypeKeyValueModelListResultModel(writer: SerializationWriter, resultTypeKeyValueModelListResultModel: Partial<ResultTypeKeyValueModelListResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!resultTypeKeyValueModelListResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ResultTypeKeyValueModel>("Data", resultTypeKeyValueModelListResultModel.data, serializeResultTypeKeyValueModel);
    writer.writeStringValue("Message", resultTypeKeyValueModelListResultModel.message);
    writer.writeNumberValue("ResultType", resultTypeKeyValueModelListResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param StringICollectionResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStringICollectionResultModel(writer: SerializationWriter, stringICollectionResultModel: Partial<StringICollectionResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!stringICollectionResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("Data", stringICollectionResultModel.data);
    writer.writeStringValue("Message", stringICollectionResultModel.message);
    writer.writeNumberValue("ResultType", stringICollectionResultModel.resultType);
}
export interface StringICollectionResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: string[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/* tslint:enable */
/* eslint-enable */
