/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
// Generated by Microsoft Kiota
// @ts-ignore
import { ServerCenterAPIRequestBuilderNavigationMetadata, type ServerCenterAPIRequestBuilder } from './serverCenterAPI/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Instantiates a new {@link RCSCAPI} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createRCSCAPI(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    
    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
    }
    
    if (serializationWriterFactory.registerDefaultSerializer) {
    }
    
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<RCSCAPI>(requestAdapter, pathParameters, RCSCAPINavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface RCSCAPI extends BaseRequestBuilder<RCSCAPI> {
    /**
     * The ServerCenterAPI property
     */
    get serverCenterAPI(): ServerCenterAPIRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const RCSCAPIUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RCSCAPINavigationMetadata: Record<Exclude<keyof RCSCAPI, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    serverCenterAPI: {
        navigationMetadata: ServerCenterAPIRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
