/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorIControllerCodeAsync>d__6.MoveNext */

using MateralReleaseCenter.ServerCenter.Abstractions.DTO.Namespace;
using MateralReleaseCenter.ServerCenter.Abstractions.RequestModel.Namespace;

namespace MateralReleaseCenter.ServerCenter.Abstractions.Controllers;

/// <summary>
/// 命名空间控制器
/// </summary>
public partial interface INamespaceController : IMergeBlockController<AddNamespaceRequestModel, EditNamespaceRequestModel, QueryNamespaceRequestModel, NamespaceDTO, NamespaceListDTO>
{
}
