/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.DTOGeneratorCodePlug+<GeneratorDTOModelAsync>d__8.MoveNext */

namespace MateralReleaseCenter.ServerCenter.Abstractions.DTO.User;

/// <summary>
/// 用户数据传输模型
/// </summary>
public partial class UserDTO : UserListDTO, IDTO
{
}
