/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorIControllerCodeAsync>d__6.MoveNext */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.DefaultData;
using MateralReleaseCenter.DeployServer.Abstractions.RequestModel.DefaultData;

namespace MateralReleaseCenter.DeployServer.Abstractions.Controllers;

/// <summary>
/// 默认数据控制器
/// </summary>
public partial interface IDefaultDataController : IMergeBlockController<AddDefaultDataRequestModel, EditDefaultDataRequestModel, QueryDefaultDataRequestModel, DefaultDataDTO, DefaultDataListDTO>
{
}
