/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorIControllerCodeAsync>d__6.MoveNext */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalEnvironment;
using MateralReleaseCenter.DeployServer.Abstractions.RequestModel.GlobalEnvironment;

namespace MateralReleaseCenter.DeployServer.Abstractions.Controllers;

/// <summary>
/// 全局环境变量控制器
/// </summary>
public partial interface IGlobalEnvironmentController : IMergeBlockController<AddGlobalEnvironmentRequestModel, EditGlobalEnvironmentRequestModel, QueryGlobalEnvironmentRequestModel, GlobalEnvironmentDTO, GlobalEnvironmentListDTO>
{
}
