/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorIControllerCodeAsync>d__6.MoveNext */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalParameter;
using MateralReleaseCenter.DeployServer.Abstractions.RequestModel.GlobalParameter;

namespace MateralReleaseCenter.DeployServer.Abstractions.Controllers;

/// <summary>
/// 全局参数控制器
/// </summary>
public partial interface IGlobalParameterController : IMergeBlockController<AddGlobalParameterRequestModel, EditGlobalParameterRequestModel, QueryGlobalParameterRequestModel, GlobalParameterDTO, GlobalParameterListDTO>
{
}
