/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, serializeResultModel, serializeSyncConfigRequestModel, type ResultModel, type SyncConfigRequestModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /EnvironmentServerAPI/ConfigurationItem/SyncConfig
 */
export interface SyncConfigRequestBuilder extends BaseRequestBuilder<SyncConfigRequestBuilder> {
    /**
     * 同步配置
     * @param body 同步配置请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     put(body: SyncConfigRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ResultModel | undefined>;
    /**
     * 同步配置
     * @param body 同步配置请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: SyncConfigRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SyncConfigRequestBuilderUriTemplate = "{+baseurl}/EnvironmentServerAPI/ConfigurationItem/SyncConfig";
/**
 * Metadata for all the requests in the request builder.
 */
export const SyncConfigRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: SyncConfigRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSyncConfigRequestModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
