/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, type ResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/DeleteFile
 */
export interface DeleteFileRequestBuilder extends BaseRequestBuilder<DeleteFileRequestBuilder> {
    /**
     * 删除文件
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     delete(requestConfiguration?: RequestConfiguration<DeleteFileRequestBuilderDeleteQueryParameters> | undefined) : Promise<ResultModel | undefined>;
    /**
     * 删除文件
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<DeleteFileRequestBuilderDeleteQueryParameters> | undefined) : RequestInformation;
}
/**
 * 删除文件
 */
export interface DeleteFileRequestBuilderDeleteQueryParameters {
    fileName?: string;
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const DeleteFileRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/DeleteFile{?fileName*,id*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const DeleteFileRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: DeleteFileRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
