/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createConfigurationItemListDTOCollectionResultModelFromDiscriminatorValue, serializeConfigurationItemListDTOCollectionResultModel, serializeQueryConfigurationItemRequestModel, type ConfigurationItemListDTOCollectionResultModel, type QueryConfigurationItemRequestModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /EnvironmentServerAPI/ConfigurationItem/GetList
 */
export interface GetListRequestBuilder extends BaseRequestBuilder<GetListRequestBuilder> {
    /**
     * 获得列表信息
     * @param body 配置项查询请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ConfigurationItemListDTOCollectionResultModel>}
     */
     post(body: QueryConfigurationItemRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ConfigurationItemListDTOCollectionResultModel | undefined>;
    /**
     * 获得列表信息
     * @param body 配置项查询请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryConfigurationItemRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetListRequestBuilderUriTemplate = "{+baseurl}/EnvironmentServerAPI/ConfigurationItem/GetList";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: GetListRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createConfigurationItemListDTOCollectionResultModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryConfigurationItemRequestModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
