/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { EnumsRequestBuilderNavigationMetadata, type EnumsRequestBuilder } from './enums/index.js';
// @ts-ignore
import { NamespaceRequestBuilderNavigationMetadata, type NamespaceRequestBuilder } from './namespace/index.js';
// @ts-ignore
import { ProjectRequestBuilderNavigationMetadata, type ProjectRequestBuilder } from './project/index.js';
// @ts-ignore
import { ServerRequestBuilderNavigationMetadata, type ServerRequestBuilder } from './server/index.js';
// @ts-ignore
import { type UserRequestBuilder, UserRequestBuilderNavigationMetadata } from './user/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI
 */
export interface ServerCenterAPIRequestBuilder extends BaseRequestBuilder<ServerCenterAPIRequestBuilder> {
    /**
     * The Enums property
     */
    get enums(): EnumsRequestBuilder;
    /**
     * The Namespace property
     */
    get namespace(): NamespaceRequestBuilder;
    /**
     * The Project property
     */
    get project(): ProjectRequestBuilder;
    /**
     * The Server property
     */
    get server(): ServerRequestBuilder;
    /**
     * The User property
     */
    get user(): UserRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ServerCenterAPIRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ServerCenterAPIRequestBuilderNavigationMetadata: Record<Exclude<keyof ServerCenterAPIRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    enums: {
        navigationMetadata: EnumsRequestBuilderNavigationMetadata,
    },
    namespace: {
        navigationMetadata: NamespaceRequestBuilderNavigationMetadata,
    },
    project: {
        navigationMetadata: ProjectRequestBuilderNavigationMetadata,
    },
    server: {
        navigationMetadata: ServerRequestBuilderNavigationMetadata,
    },
    user: {
        navigationMetadata: UserRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
