/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGuidResultModelFromDiscriminatorValue, serializeAddGlobalParameterRequestModel, serializeGuidResultModel, type AddGlobalParameterRequestModel, type GuidResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/GlobalParameter/Add
 */
export interface AddRequestBuilder extends BaseRequestBuilder<AddRequestBuilder> {
    /**
     * @param body 全局参数添加请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GuidResultModel>}
     */
     post(body: AddGlobalParameterRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GuidResultModel | undefined>;
    /**
     * @param body 全局参数添加请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AddGlobalParameterRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AddRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/GlobalParameter/Add";
/**
 * Metadata for all the requests in the request builder.
 */
export const AddRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AddRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createGuidResultModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAddGlobalParameterRequestModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
