/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AddRequestBuilderRequestsMetadata, type AddRequestBuilder } from './add/index.js';
// @ts-ignore
import { ChangePasswordRequestBuilderRequestsMetadata, type ChangePasswordRequestBuilder } from './changePassword/index.js';
// @ts-ignore
import { DeleteRequestBuilderRequestsMetadata, type DeleteRequestBuilder } from './delete/index.js';
// @ts-ignore
import { EditRequestBuilderRequestsMetadata, type EditRequestBuilder } from './edit/index.js';
// @ts-ignore
import { GetInfoRequestBuilderRequestsMetadata, type GetInfoRequestBuilder } from './getInfo/index.js';
// @ts-ignore
import { GetListRequestBuilderRequestsMetadata, type GetListRequestBuilder } from './getList/index.js';
// @ts-ignore
import { GetLoginUserInfoRequestBuilderRequestsMetadata, type GetLoginUserInfoRequestBuilder } from './getLoginUserInfo/index.js';
// @ts-ignore
import { LoginRequestBuilderRequestsMetadata, type LoginRequestBuilder } from './login/index.js';
// @ts-ignore
import { ResetPasswordRequestBuilderRequestsMetadata, type ResetPasswordRequestBuilder } from './resetPassword/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/User
 */
export interface UserRequestBuilder extends BaseRequestBuilder<UserRequestBuilder> {
    /**
     * The Add property
     */
    get add(): AddRequestBuilder;
    /**
     * The ChangePassword property
     */
    get changePassword(): ChangePasswordRequestBuilder;
    /**
     * The DeletePath property
     */
    get deletePath(): DeleteRequestBuilder;
    /**
     * The Edit property
     */
    get edit(): EditRequestBuilder;
    /**
     * The GetInfo property
     */
    get getInfo(): GetInfoRequestBuilder;
    /**
     * The GetList property
     */
    get getList(): GetListRequestBuilder;
    /**
     * The GetLoginUserInfo property
     */
    get getLoginUserInfo(): GetLoginUserInfoRequestBuilder;
    /**
     * The Login property
     */
    get login(): LoginRequestBuilder;
    /**
     * The ResetPassword property
     */
    get resetPassword(): ResetPasswordRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const UserRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/User";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UserRequestBuilderNavigationMetadata: Record<Exclude<keyof UserRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    add: {
        requestsMetadata: AddRequestBuilderRequestsMetadata,
    },
    changePassword: {
        requestsMetadata: ChangePasswordRequestBuilderRequestsMetadata,
    },
    deletePath: {
        requestsMetadata: DeleteRequestBuilderRequestsMetadata,
    },
    edit: {
        requestsMetadata: EditRequestBuilderRequestsMetadata,
    },
    getInfo: {
        requestsMetadata: GetInfoRequestBuilderRequestsMetadata,
    },
    getList: {
        requestsMetadata: GetListRequestBuilderRequestsMetadata,
    },
    getLoginUserInfo: {
        requestsMetadata: GetLoginUserInfoRequestBuilderRequestsMetadata,
    },
    login: {
        requestsMetadata: LoginRequestBuilderRequestsMetadata,
    },
    resetPassword: {
        requestsMetadata: ResetPasswordRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
