/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorIServicesCodeAsync */

using MateralReleaseCenter.ServerCenter.Abstractions.DTO.Namespace;
using MateralReleaseCenter.ServerCenter.Abstractions.Services.Models.Namespace;

namespace MateralReleaseCenter.ServerCenter.Abstractions.Services
{
    /// <summary>
    /// 命名空间服务
    /// </summary>
    public partial interface INamespaceService : IBaseService<AddNamespaceModel, EditNamespaceModel, QueryNamespaceModel, NamespaceDTO, NamespaceListDTO>
    {
    }
}
