/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorIServicesCodeAsync */

using MateralReleaseCenter.ServerCenter.Abstractions.DTO.Project;
using MateralReleaseCenter.ServerCenter.Abstractions.Services.Models.Project;

namespace MateralReleaseCenter.ServerCenter.Abstractions.Services
{
    /// <summary>
    /// 项目服务
    /// </summary>
    public partial interface IProjectService : IBaseService<AddProjectModel, EditProjectModel, QueryProjectModel, ProjectDTO, ProjectListDTO>
    {
    }
}
