/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEnvironmentServerListDTOListResultModelFromDiscriminatorValue, type EnvironmentServerListDTOListResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/Server/GetEnvironmentServerList
 */
export interface GetEnvironmentServerListRequestBuilder extends BaseRequestBuilder<GetEnvironmentServerListRequestBuilder> {
    /**
     * 获得环境服务程序列表
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EnvironmentServerListDTOListResultModel>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EnvironmentServerListDTOListResultModel | undefined>;
    /**
     * 获得环境服务程序列表
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetEnvironmentServerListRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/Server/GetEnvironmentServerList";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetEnvironmentServerListRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetEnvironmentServerListRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createEnvironmentServerListDTOListResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
