/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.DTOGeneratorCodePlug+<GeneratorDTOModelAsync>d__8.MoveNext */

namespace MateralReleaseCenter.DeployServer.Abstractions.DTO.ApplicationInfo;

/// <summary>
/// 应用程序信息数据传输模型
/// </summary>
public partial class ApplicationInfoDTO : ApplicationInfoListDTO, IDTO
{
}
