/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, type ResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/ClearConsoleMessages
 */
export interface ClearConsoleMessagesRequestBuilder extends BaseRequestBuilder<ClearConsoleMessagesRequestBuilder> {
    /**
     * 清空控制台信息
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     delete(requestConfiguration?: RequestConfiguration<ClearConsoleMessagesRequestBuilderDeleteQueryParameters> | undefined) : Promise<ResultModel | undefined>;
    /**
     * 清空控制台信息
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<ClearConsoleMessagesRequestBuilderDeleteQueryParameters> | undefined) : RequestInformation;
}
/**
 * 清空控制台信息
 */
export interface ClearConsoleMessagesRequestBuilderDeleteQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const ClearConsoleMessagesRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/ClearConsoleMessages{?id*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ClearConsoleMessagesRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: ClearConsoleMessagesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
