/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorServiceImplsCodeAsync */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalEnvironment;
using MateralReleaseCenter.DeployServer.Abstractions.Services.Models.GlobalEnvironment;

namespace MateralReleaseCenter.DeployServer.Application.Services
{
    /// <summary>
    /// 全局环境变量服务
    /// </summary>
    public partial class GlobalEnvironmentServiceImpl : BaseServiceImpl<AddGlobalEnvironmentModel, EditGlobalEnvironmentModel, QueryGlobalEnvironmentModel, GlobalEnvironmentDTO, GlobalEnvironmentListDTO, IGlobalEnvironmentRepository, GlobalEnvironment, IDeployServerUnitOfWork>, IGlobalEnvironmentService, IScopedDependency<IGlobalEnvironmentService>
    {
    }
}
