/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorServiceImplsCodeAsync */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalParameter;
using MateralReleaseCenter.DeployServer.Abstractions.Services.Models.GlobalParameter;

namespace MateralReleaseCenter.DeployServer.Application.Services
{
    /// <summary>
    /// 全局参数服务
    /// </summary>
    public partial class GlobalParameterServiceImpl : BaseServiceImpl<AddGlobalParameterModel, EditGlobalParameterModel, QueryGlobalParameterModel, GlobalParameterDTO, GlobalParameterListDTO, IGlobalParameterRepository, GlobalParameter, IDeployServerUnitOfWork>, IGlobalParameterService, IScopedDependency<IGlobalParameterService>
    {
    }
}
