/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ApplicationInfoRequestBuilderNavigationMetadata, type ApplicationInfoRequestBuilder } from './applicationInfo/index.js';
// @ts-ignore
import { DefaultDataRequestBuilderNavigationMetadata, type DefaultDataRequestBuilder } from './defaultData/index.js';
// @ts-ignore
import { EnumsRequestBuilderNavigationMetadata, type EnumsRequestBuilder } from './enums/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI
 */
export interface DeployServerAPIRequestBuilder extends BaseRequestBuilder<DeployServerAPIRequestBuilder> {
    /**
     * The ApplicationInfo property
     */
    get applicationInfo(): ApplicationInfoRequestBuilder;
    /**
     * The DefaultData property
     */
    get defaultData(): DefaultDataRequestBuilder;
    /**
     * The Enums property
     */
    get enums(): EnumsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DeployServerAPIRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DeployServerAPIRequestBuilderNavigationMetadata: Record<Exclude<keyof DeployServerAPIRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    applicationInfo: {
        navigationMetadata: ApplicationInfoRequestBuilderNavigationMetadata,
    },
    defaultData: {
        navigationMetadata: DefaultDataRequestBuilderNavigationMetadata,
    },
    enums: {
        navigationMetadata: EnumsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
