/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createStringResultModelFromDiscriminatorValue, type StringResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/Server/GetBaseUrl
 */
export interface GetBaseUrlRequestBuilder extends BaseRequestBuilder<GetBaseUrlRequestBuilder> {
    /**
     * 获得基础地址
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<StringResultModel>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<StringResultModel | undefined>;
    /**
     * 获得基础地址
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetBaseUrlRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/Server/GetBaseUrl";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetBaseUrlRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetBaseUrlRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createStringResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
