/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { GetAllResultTypeRequestBuilderRequestsMetadata, type GetAllResultTypeRequestBuilder } from './getAllResultType/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/Enums
 */
export interface EnumsRequestBuilder extends BaseRequestBuilder<EnumsRequestBuilder> {
    /**
     * The GetAllResultType property
     */
    get getAllResultType(): GetAllResultTypeRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const EnumsRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/Enums";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EnumsRequestBuilderNavigationMetadata: Record<Exclude<keyof EnumsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    getAllResultType: {
        requestsMetadata: GetAllResultTypeRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
