/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesModelGeneratorCodePlug+<GeneratorEditModelAsync>d__9.MoveNext */

namespace MateralReleaseCenter.DeployServer.Abstractions.Services.Models.GlobalParameter;
/// <summary>
/// 全局参数修改模型
/// </summary>
public partial class EditGlobalParameterModel : IEditServiceModel
{
    /// <summary>
    /// 唯一标识
    /// </summary>
    [Required(ErrorMessage = "唯一标识为空")]
    public Guid ID { get; set; }
    /// <summary>
    /// 应用程序类型
    /// </summary>
    [Required(ErrorMessage = "应用程序类型为空")]
    public ApplicationTypeEnum ApplicationType { get; set; }
    /// <summary>
    /// 名称
    /// </summary>
    [Required(ErrorMessage = "名称为空")]
    public string Name { get; set; } = string.Empty;
    /// <summary>
    /// 值
    /// </summary>
    [Required(ErrorMessage = "值为空")]
    public string Value { get; set; } = string.Empty;
}
