/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
// Generated by Microsoft Kiota
// @ts-ignore
import { EnvironmentServerAPIRequestBuilderNavigationMetadata, type EnvironmentServerAPIRequestBuilder } from './environmentServerAPI/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Instantiates a new {@link RCESAPI} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createRCESAPI(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    
    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
    }
    
    if (serializationWriterFactory.registerDefaultSerializer) {
    }
    
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<RCESAPI>(requestAdapter, pathParameters, RCESAPINavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface RCESAPI extends BaseRequestBuilder<RCESAPI> {
    /**
     * The EnvironmentServerAPI property
     */
    get environmentServerAPI(): EnvironmentServerAPIRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const RCESAPIUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RCESAPINavigationMetadata: Record<Exclude<keyof RCESAPI, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    environmentServerAPI: {
        navigationMetadata: EnvironmentServerAPIRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
