/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RequesetModelGeneratorCodePlug+<GeneratorEditRequestModelAsync>d__9.MoveNext */

namespace MateralReleaseCenter.ServerCenter.Abstractions.RequestModel.User;
/// <summary>
/// 用户修改请求模型
/// </summary>
public partial class EditUserRequestModel : IEditRequestModel
{
    /// <summary>
    /// 唯一标识
    /// </summary>
    [Required(ErrorMessage = "唯一标识为空")]
    public Guid ID { get; set; }
    /// <summary>
    /// 姓名
    /// </summary>
    [Required(ErrorMessage = "姓名为空"), StringLength(100, ErrorMessage = "姓名最多100个字符")]
    public string Name { get; set; } = string.Empty;
}
