/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
// Generated by Microsoft Kiota
// @ts-ignore
import { DeployServerAPIRequestBuilderNavigationMetadata, type DeployServerAPIRequestBuilder } from './deployServerAPI/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Instantiates a new {@link RCDSAPI} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createRCDSAPI(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();

    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
    }

    if (serializationWriterFactory.registerDefaultSerializer) {
    }

    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<RCDSAPI>(requestAdapter, pathParameters, RCDSAPINavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface RCDSAPI extends BaseRequestBuilder<RCDSAPI> {
    /**
     * The DeployServerAPI property
     */
    get deployServerAPI(): DeployServerAPIRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const RCDSAPIUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RCDSAPINavigationMetadata: Record<Exclude<keyof RCDSAPI, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    deployServerAPI: {
        navigationMetadata: DeployServerAPIRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
