/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, type ResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/ApplyLasetReleases
 */
export interface ApplyLasetReleasesRequestBuilder extends BaseRequestBuilder<ApplyLasetReleasesRequestBuilder> {
    /**
     * 应用最好一个发布
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     put(requestConfiguration?: RequestConfiguration<ApplyLasetReleasesRequestBuilderPutQueryParameters> | undefined) : Promise<ResultModel | undefined>;
    /**
     * 应用最好一个发布
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(requestConfiguration?: RequestConfiguration<ApplyLasetReleasesRequestBuilderPutQueryParameters> | undefined) : RequestInformation;
}
/**
 * 应用最好一个发布
 */
export interface ApplyLasetReleasesRequestBuilderPutQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const ApplyLasetReleasesRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/ApplyLasetReleases{?id*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ApplyLasetReleasesRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: ApplyLasetReleasesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
