/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorRepositoryImplCodeAsync>d__12.MoveNext */

namespace MateralReleaseCenter.ServerCenter.Repository.Repositories;
/// <summary>
/// 命名空间仓储
/// </summary>

public partial class NamespaceRepositoryImpl(ServerCenterDBContext dbContext) : ServerCenterRepositoryImpl<Namespace>(dbContext), INamespaceRepository, IScopedDependency<INamespaceRepository>
{

}
