/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorRepositoryImplCodeAsync>d__12.MoveNext */

namespace MateralReleaseCenter.ServerCenter.Repository.Repositories;
/// <summary>
/// 项目仓储
/// </summary>

public partial class ProjectRepositoryImpl(ServerCenterDBContext dbContext) : ServerCenterRepositoryImpl<Project>(dbContext), IProjectRepository, IScopedDependency<IProjectRepository>
{

}
