/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorRepositoryImplCodeAsync>d__12.MoveNext */

namespace MateralReleaseCenter.ServerCenter.Repository.Repositories;
/// <summary>
/// 用户仓储
/// </summary>

public partial class UserRepositoryImpl(ServerCenterDBContext dbContext) : ServerCenterRepositoryImpl<User>(dbContext), IUserRepository, IScopedDependency<IUserRepository>
{

}
