/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ConfigurationItemRequestBuilderNavigationMetadata, type ConfigurationItemRequestBuilder } from './configurationItem/index.js';
// @ts-ignore
import { EnumsRequestBuilderNavigationMetadata, type EnumsRequestBuilder } from './enums/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /EnvironmentServerAPI
 */
export interface EnvironmentServerAPIRequestBuilder extends BaseRequestBuilder<EnvironmentServerAPIRequestBuilder> {
    /**
     * The ConfigurationItem property
     */
    get configurationItem(): ConfigurationItemRequestBuilder;
    /**
     * The Enums property
     */
    get enums(): EnumsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const EnvironmentServerAPIRequestBuilderUriTemplate = "{+baseurl}/EnvironmentServerAPI";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EnvironmentServerAPIRequestBuilderNavigationMetadata: Record<Exclude<keyof EnvironmentServerAPIRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    configurationItem: {
        navigationMetadata: ConfigurationItemRequestBuilderNavigationMetadata,
    },
    enums: {
        navigationMetadata: EnumsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
