// <auto-generated />
using System;
using MateralReleaseCenter.DeployServer.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MateralReleaseCenter.DeployServer.Repository.Migrations
{
    [DbContext(typeof(DeployServerDBContext))]
    [Migration("20260304075200_ApplicationInfo_Add_RepositoryUrl_AuthToken")]
    partial class ApplicationInfo_Add_RepositoryUrl_AuthToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("MateralReleaseCenter.DeployServer.Abstractions.Domain.ApplicationInfo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("ApplicationType")
                        .HasColumnType("INTEGER")
                        .HasComment("应用程序类型");

                    b.Property<string>("AuthToken")
                        .HasColumnType("TEXT")
                        .HasComment("授权令牌");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncrementalUpdating")
                        .HasColumnType("INTEGER")
                        .HasComment("增量更新");

                    b.Property<string>("MainModule")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("主模块");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("名称");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("TEXT")
                        .HasComment("仓库地址");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("根路径");

                    b.Property<string>("RunParams")
                        .HasColumnType("TEXT")
                        .HasComment("运行参数");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ApplicationInfo", t =>
                        {
                            t.HasComment("应用程序信息");
                        });
                });

            modelBuilder.Entity("MateralReleaseCenter.DeployServer.Abstractions.Domain.DefaultData", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("ApplicationType")
                        .HasColumnType("INTEGER")
                        .HasComment("应用程序类型");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("数据");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("键");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("DefaultData", t =>
                        {
                            t.HasComment("默认数据");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
