// <auto-generated />
using System;
using MateralReleaseCenter.DeployServer.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MateralReleaseCenter.DeployServer.Repository.Migrations
{
    [DbContext(typeof(DeployServerDBContext))]
    [Migration("20260318020422_Add_GlobalParameter_And_GlobalEnvironment")]
    partial class Add_GlobalParameter_And_GlobalEnvironment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("MateralReleaseCenter.DeployServer.Abstractions.Domain.ApplicationInfo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("ApplicationType")
                        .HasColumnType("INTEGER")
                        .HasComment("应用程序类型");

                    b.Property<string>("AuthToken")
                        .HasColumnType("TEXT")
                        .HasComment("授权令牌");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environments")
                        .HasColumnType("TEXT")
                        .HasComment("环境变量");

                    b.Property<bool>("IsIncrementalUpdating")
                        .HasColumnType("INTEGER")
                        .HasComment("增量更新");

                    b.Property<string>("MainModule")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("主模块");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("名称");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("TEXT")
                        .HasComment("仓库地址");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("根路径");

                    b.Property<string>("RunParams")
                        .HasColumnType("TEXT")
                        .HasComment("运行参数");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ApplicationInfo", t =>
                        {
                            t.HasComment("应用程序信息");
                        });
                });

            modelBuilder.Entity("MateralReleaseCenter.DeployServer.Abstractions.Domain.GlobalEnvironment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("ApplicationType")
                        .HasColumnType("INTEGER")
                        .HasComment("应用程序类型");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasComment("描述");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("键");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("值");

                    b.HasKey("ID");

                    b.ToTable("GlobalEnvironment", t =>
                        {
                            t.HasComment("全局环境变量");
                        });
                });

            modelBuilder.Entity("MateralReleaseCenter.DeployServer.Abstractions.Domain.GlobalParameter", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("ApplicationType")
                        .HasColumnType("INTEGER")
                        .HasComment("应用程序类型");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("名称");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("值");

                    b.HasKey("ID");

                    b.ToTable("GlobalParameter", t =>
                        {
                            t.HasComment("全局参数");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
