/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * 命名空间添加请求模型
 */
export interface AddNamespaceRequestModel extends Parsable {
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 名称
     */
    name?: string | null;
    /**
     * 命名空间唯一标识
     */
    projectID?: Guid | null;
}
/**
 * 项目添加请求模型
 */
export interface AddProjectRequestModel extends Parsable {
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 名称
     */
    name?: string | null;
}
/**
 * 用户添加请求模型
 */
export interface AddUserRequestModel extends Parsable {
    /**
     * 账号
     */
    account?: string | null;
    /**
     * 姓名
     */
    name?: string | null;
}
/**
 * 更改密码请求模型
 */
export interface ChangePasswordRequestModel extends Parsable {
    /**
     * 新密码
     */
    newPassword?: string | null;
    /**
     * 旧密码
     */
    oldPassword?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AddNamespaceRequestModel}
 */
// @ts-ignore
export function createAddNamespaceRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAddNamespaceRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AddProjectRequestModel}
 */
// @ts-ignore
export function createAddProjectRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAddProjectRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AddUserRequestModel}
 */
// @ts-ignore
export function createAddUserRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAddUserRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ChangePasswordRequestModel}
 */
// @ts-ignore
export function createChangePasswordRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChangePasswordRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DeployListDTO}
 */
// @ts-ignore
export function createDeployListDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDeployListDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DeployListDTOListResultModel}
 */
// @ts-ignore
export function createDeployListDTOListResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDeployListDTOListResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EditNamespaceRequestModel}
 */
// @ts-ignore
export function createEditNamespaceRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEditNamespaceRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EditProjectRequestModel}
 */
// @ts-ignore
export function createEditProjectRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEditProjectRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EditUserRequestModel}
 */
// @ts-ignore
export function createEditUserRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEditUserRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EnvironmentServerListDTO}
 */
// @ts-ignore
export function createEnvironmentServerListDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEnvironmentServerListDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EnvironmentServerListDTOListResultModel}
 */
// @ts-ignore
export function createEnvironmentServerListDTOListResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEnvironmentServerListDTOListResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GuidResultModel}
 */
// @ts-ignore
export function createGuidResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGuidResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginRequestModel}
 */
// @ts-ignore
export function createLoginRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginResultDTO}
 */
// @ts-ignore
export function createLoginResultDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginResultDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginResultDTOResultModel}
 */
// @ts-ignore
export function createLoginResultDTOResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginResultDTOResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {NamespaceDTO}
 */
// @ts-ignore
export function createNamespaceDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoNamespaceDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {NamespaceDTOResultModel}
 */
// @ts-ignore
export function createNamespaceDTOResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoNamespaceDTOResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {NamespaceListDTOCollectionResultModel}
 */
// @ts-ignore
export function createNamespaceListDTOCollectionResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoNamespaceListDTOCollectionResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {NamespaceListDTO}
 */
// @ts-ignore
export function createNamespaceListDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoNamespaceListDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PageModel}
 */
// @ts-ignore
export function createPageModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPageModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProjectDTO}
 */
// @ts-ignore
export function createProjectDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProjectDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProjectDTOResultModel}
 */
// @ts-ignore
export function createProjectDTOResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProjectDTOResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProjectListDTOCollectionResultModel}
 */
// @ts-ignore
export function createProjectListDTOCollectionResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProjectListDTOCollectionResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProjectListDTO}
 */
// @ts-ignore
export function createProjectListDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProjectListDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryNamespaceRequestModel}
 */
// @ts-ignore
export function createQueryNamespaceRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryNamespaceRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryProjectRequestModel}
 */
// @ts-ignore
export function createQueryProjectRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryProjectRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryUserRequestModel}
 */
// @ts-ignore
export function createQueryUserRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryUserRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RangeModel}
 */
// @ts-ignore
export function createRangeModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRangeModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResultModel}
 */
// @ts-ignore
export function createResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResultTypeKeyValueModel}
 */
// @ts-ignore
export function createResultTypeKeyValueModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResultTypeKeyValueModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResultTypeKeyValueModelListResultModel}
 */
// @ts-ignore
export function createResultTypeKeyValueModelListResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResultTypeKeyValueModelListResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StringResultModel}
 */
// @ts-ignore
export function createStringResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStringResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UserDTO}
 */
// @ts-ignore
export function createUserDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUserDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UserDTOResultModel}
 */
// @ts-ignore
export function createUserDTOResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUserDTOResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UserListDTOCollectionResultModel}
 */
// @ts-ignore
export function createUserListDTOCollectionResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUserListDTOCollectionResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UserListDTO}
 */
// @ts-ignore
export function createUserListDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUserListDTO;
}
/**
 * 发布服务数据传输模型
 */
export interface DeployListDTO extends Parsable {
    /**
     * 访问Url
     */
    accessUrl?: string | null;
    /**
     * 主机
     */
    host?: string | null;
    /**
     * 名称
     */
    name?: string | null;
    /**
     * 端口
     */
    port?: number | null;
}
export interface DeployListDTOListResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: DeployListDTO[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * The deserialization information for the current model
 * @param AddNamespaceRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAddNamespaceRequestModel(addNamespaceRequestModel: Partial<AddNamespaceRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Description": n => { addNamespaceRequestModel.description = n.getStringValue(); },
        "Name": n => { addNamespaceRequestModel.name = n.getStringValue(); },
        "ProjectID": n => { addNamespaceRequestModel.projectID = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AddProjectRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAddProjectRequestModel(addProjectRequestModel: Partial<AddProjectRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Description": n => { addProjectRequestModel.description = n.getStringValue(); },
        "Name": n => { addProjectRequestModel.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AddUserRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAddUserRequestModel(addUserRequestModel: Partial<AddUserRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Account": n => { addUserRequestModel.account = n.getStringValue(); },
        "Name": n => { addUserRequestModel.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ChangePasswordRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoChangePasswordRequestModel(changePasswordRequestModel: Partial<ChangePasswordRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "NewPassword": n => { changePasswordRequestModel.newPassword = n.getStringValue(); },
        "OldPassword": n => { changePasswordRequestModel.oldPassword = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DeployListDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDeployListDTO(deployListDTO: Partial<DeployListDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "AccessUrl": n => { deployListDTO.accessUrl = n.getStringValue(); },
        "Host": n => { deployListDTO.host = n.getStringValue(); },
        "Name": n => { deployListDTO.name = n.getStringValue(); },
        "Port": n => { deployListDTO.port = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DeployListDTOListResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDeployListDTOListResultModel(deployListDTOListResultModel: Partial<DeployListDTOListResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { deployListDTOListResultModel.data = n.getCollectionOfObjectValues<DeployListDTO>(createDeployListDTOFromDiscriminatorValue); },
        "Message": n => { deployListDTOListResultModel.message = n.getStringValue(); },
        "ResultType": n => { deployListDTOListResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EditNamespaceRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEditNamespaceRequestModel(editNamespaceRequestModel: Partial<EditNamespaceRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Description": n => { editNamespaceRequestModel.description = n.getStringValue(); },
        "ID": n => { editNamespaceRequestModel.iD = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EditProjectRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEditProjectRequestModel(editProjectRequestModel: Partial<EditProjectRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Description": n => { editProjectRequestModel.description = n.getStringValue(); },
        "ID": n => { editProjectRequestModel.iD = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EditUserRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEditUserRequestModel(editUserRequestModel: Partial<EditUserRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ID": n => { editUserRequestModel.iD = n.getGuidValue(); },
        "Name": n => { editUserRequestModel.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EnvironmentServerListDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEnvironmentServerListDTO(environmentServerListDTO: Partial<EnvironmentServerListDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Host": n => { environmentServerListDTO.host = n.getStringValue(); },
        "Name": n => { environmentServerListDTO.name = n.getStringValue(); },
        "Port": n => { environmentServerListDTO.port = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EnvironmentServerListDTOListResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEnvironmentServerListDTOListResultModel(environmentServerListDTOListResultModel: Partial<EnvironmentServerListDTOListResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { environmentServerListDTOListResultModel.data = n.getCollectionOfObjectValues<EnvironmentServerListDTO>(createEnvironmentServerListDTOFromDiscriminatorValue); },
        "Message": n => { environmentServerListDTOListResultModel.message = n.getStringValue(); },
        "ResultType": n => { environmentServerListDTOListResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param GuidResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGuidResultModel(guidResultModel: Partial<GuidResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { guidResultModel.data = n.getGuidValue(); },
        "Message": n => { guidResultModel.message = n.getStringValue(); },
        "ResultType": n => { guidResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginRequestModel(loginRequestModel: Partial<LoginRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Account": n => { loginRequestModel.account = n.getStringValue(); },
        "Password": n => { loginRequestModel.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginResultDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginResultDTO(loginResultDTO: Partial<LoginResultDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "ExpiredTime": n => { loginResultDTO.expiredTime = n.getNumberValue(); },
        "Token": n => { loginResultDTO.token = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginResultDTOResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginResultDTOResultModel(loginResultDTOResultModel: Partial<LoginResultDTOResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { loginResultDTOResultModel.data = n.getObjectValue<LoginResultDTO>(createLoginResultDTOFromDiscriminatorValue); },
        "Message": n => { loginResultDTOResultModel.message = n.getStringValue(); },
        "ResultType": n => { loginResultDTOResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param NamespaceDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoNamespaceDTO(namespaceDTO: Partial<NamespaceDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "CreateTime": n => { namespaceDTO.createTime = n.getDateValue(); },
        "Description": n => { namespaceDTO.description = n.getStringValue(); },
        "ID": n => { namespaceDTO.iD = n.getGuidValue(); },
        "Name": n => { namespaceDTO.name = n.getStringValue(); },
        "ProjectID": n => { namespaceDTO.projectID = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param NamespaceDTOResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoNamespaceDTOResultModel(namespaceDTOResultModel: Partial<NamespaceDTOResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { namespaceDTOResultModel.data = n.getObjectValue<NamespaceDTO>(createNamespaceDTOFromDiscriminatorValue); },
        "Message": n => { namespaceDTOResultModel.message = n.getStringValue(); },
        "ResultType": n => { namespaceDTOResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param NamespaceListDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoNamespaceListDTO(namespaceListDTO: Partial<NamespaceListDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "CreateTime": n => { namespaceListDTO.createTime = n.getDateValue(); },
        "Description": n => { namespaceListDTO.description = n.getStringValue(); },
        "ID": n => { namespaceListDTO.iD = n.getGuidValue(); },
        "Name": n => { namespaceListDTO.name = n.getStringValue(); },
        "ProjectID": n => { namespaceListDTO.projectID = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param NamespaceListDTOCollectionResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoNamespaceListDTOCollectionResultModel(namespaceListDTOCollectionResultModel: Partial<NamespaceListDTOCollectionResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { namespaceListDTOCollectionResultModel.data = n.getCollectionOfObjectValues<NamespaceListDTO>(createNamespaceListDTOFromDiscriminatorValue); },
        "Message": n => { namespaceListDTOCollectionResultModel.message = n.getStringValue(); },
        "PageModel": n => { namespaceListDTOCollectionResultModel.pageModel = n.getObjectValue<PageModel>(createPageModelFromDiscriminatorValue); },
        "RangeModel": n => { namespaceListDTOCollectionResultModel.rangeModel = n.getObjectValue<RangeModel>(createRangeModelFromDiscriminatorValue); },
        "ResultType": n => { namespaceListDTOCollectionResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PageModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPageModel(pageModel: Partial<PageModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "DataCount": n => { pageModel.dataCount = n.getNumberValue(); },
        "IsAsc": n => { pageModel.isAsc = n.getBooleanValue(); },
        "PageCount": n => { pageModel.pageCount = n.getNumberValue(); },
        "PageIndex": n => { pageModel.pageIndex = n.getNumberValue(); },
        "PageSize": n => { pageModel.pageSize = n.getNumberValue(); },
        "Skip": n => { pageModel.skip = n.getNumberValue(); },
        "SortPropertyName": n => { pageModel.sortPropertyName = n.getStringValue(); },
        "StartIndex": n => { pageModel.startIndex = n.getNumberValue(); },
        "Take": n => { pageModel.take = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProjectDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProjectDTO(projectDTO: Partial<ProjectDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "CreateTime": n => { projectDTO.createTime = n.getDateValue(); },
        "Description": n => { projectDTO.description = n.getStringValue(); },
        "ID": n => { projectDTO.iD = n.getGuidValue(); },
        "Name": n => { projectDTO.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProjectDTOResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProjectDTOResultModel(projectDTOResultModel: Partial<ProjectDTOResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { projectDTOResultModel.data = n.getObjectValue<ProjectDTO>(createProjectDTOFromDiscriminatorValue); },
        "Message": n => { projectDTOResultModel.message = n.getStringValue(); },
        "ResultType": n => { projectDTOResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProjectListDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProjectListDTO(projectListDTO: Partial<ProjectListDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "CreateTime": n => { projectListDTO.createTime = n.getDateValue(); },
        "Description": n => { projectListDTO.description = n.getStringValue(); },
        "ID": n => { projectListDTO.iD = n.getGuidValue(); },
        "Name": n => { projectListDTO.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProjectListDTOCollectionResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProjectListDTOCollectionResultModel(projectListDTOCollectionResultModel: Partial<ProjectListDTOCollectionResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { projectListDTOCollectionResultModel.data = n.getCollectionOfObjectValues<ProjectListDTO>(createProjectListDTOFromDiscriminatorValue); },
        "Message": n => { projectListDTOCollectionResultModel.message = n.getStringValue(); },
        "PageModel": n => { projectListDTOCollectionResultModel.pageModel = n.getObjectValue<PageModel>(createPageModelFromDiscriminatorValue); },
        "RangeModel": n => { projectListDTOCollectionResultModel.rangeModel = n.getObjectValue<RangeModel>(createRangeModelFromDiscriminatorValue); },
        "ResultType": n => { projectListDTOCollectionResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QueryNamespaceRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryNamespaceRequestModel(queryNamespaceRequestModel: Partial<QueryNamespaceRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Description": n => { queryNamespaceRequestModel.description = n.getStringValue(); },
        "IDs": n => { queryNamespaceRequestModel.iDs = n.getCollectionOfPrimitiveValues<Guid>(); },
        "IsAsc": n => { queryNamespaceRequestModel.isAsc = n.getBooleanValue(); },
        "MaxCreateTime": n => { queryNamespaceRequestModel.maxCreateTime = n.getDateValue(); },
        "MinCreateTime": n => { queryNamespaceRequestModel.minCreateTime = n.getDateValue(); },
        "Name": n => { queryNamespaceRequestModel.name = n.getStringValue(); },
        "PageIndex": n => { queryNamespaceRequestModel.pageIndex = n.getNumberValue(); },
        "PageSize": n => { queryNamespaceRequestModel.pageSize = n.getNumberValue(); },
        "ProjectID": n => { queryNamespaceRequestModel.projectID = n.getGuidValue(); },
        "Skip": n => { queryNamespaceRequestModel.skip = n.getNumberValue(); },
        "SortPropertyName": n => { queryNamespaceRequestModel.sortPropertyName = n.getStringValue(); },
        "Take": n => { queryNamespaceRequestModel.take = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QueryProjectRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryProjectRequestModel(queryProjectRequestModel: Partial<QueryProjectRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Description": n => { queryProjectRequestModel.description = n.getStringValue(); },
        "IDs": n => { queryProjectRequestModel.iDs = n.getCollectionOfPrimitiveValues<Guid>(); },
        "IsAsc": n => { queryProjectRequestModel.isAsc = n.getBooleanValue(); },
        "MaxCreateTime": n => { queryProjectRequestModel.maxCreateTime = n.getDateValue(); },
        "MinCreateTime": n => { queryProjectRequestModel.minCreateTime = n.getDateValue(); },
        "Name": n => { queryProjectRequestModel.name = n.getStringValue(); },
        "PageIndex": n => { queryProjectRequestModel.pageIndex = n.getNumberValue(); },
        "PageSize": n => { queryProjectRequestModel.pageSize = n.getNumberValue(); },
        "Skip": n => { queryProjectRequestModel.skip = n.getNumberValue(); },
        "SortPropertyName": n => { queryProjectRequestModel.sortPropertyName = n.getStringValue(); },
        "Take": n => { queryProjectRequestModel.take = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QueryUserRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryUserRequestModel(queryUserRequestModel: Partial<QueryUserRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Account": n => { queryUserRequestModel.account = n.getStringValue(); },
        "IDs": n => { queryUserRequestModel.iDs = n.getCollectionOfPrimitiveValues<Guid>(); },
        "IsAsc": n => { queryUserRequestModel.isAsc = n.getBooleanValue(); },
        "MaxCreateTime": n => { queryUserRequestModel.maxCreateTime = n.getDateValue(); },
        "MinCreateTime": n => { queryUserRequestModel.minCreateTime = n.getDateValue(); },
        "Name": n => { queryUserRequestModel.name = n.getStringValue(); },
        "PageIndex": n => { queryUserRequestModel.pageIndex = n.getNumberValue(); },
        "PageSize": n => { queryUserRequestModel.pageSize = n.getNumberValue(); },
        "Skip": n => { queryUserRequestModel.skip = n.getNumberValue(); },
        "SortPropertyName": n => { queryUserRequestModel.sortPropertyName = n.getStringValue(); },
        "Take": n => { queryUserRequestModel.take = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RangeModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRangeModel(rangeModel: Partial<RangeModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "DataCount": n => { rangeModel.dataCount = n.getNumberValue(); },
        "IsAsc": n => { rangeModel.isAsc = n.getBooleanValue(); },
        "Skip": n => { rangeModel.skip = n.getNumberValue(); },
        "SortPropertyName": n => { rangeModel.sortPropertyName = n.getStringValue(); },
        "Take": n => { rangeModel.take = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResultModel(resultModel: Partial<ResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Message": n => { resultModel.message = n.getStringValue(); },
        "ResultType": n => { resultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ResultTypeKeyValueModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResultTypeKeyValueModel(resultTypeKeyValueModel: Partial<ResultTypeKeyValueModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Key": n => { resultTypeKeyValueModel.key = n.getNumberValue(); },
        "Value": n => { resultTypeKeyValueModel.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ResultTypeKeyValueModelListResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResultTypeKeyValueModelListResultModel(resultTypeKeyValueModelListResultModel: Partial<ResultTypeKeyValueModelListResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { resultTypeKeyValueModelListResultModel.data = n.getCollectionOfObjectValues<ResultTypeKeyValueModel>(createResultTypeKeyValueModelFromDiscriminatorValue); },
        "Message": n => { resultTypeKeyValueModelListResultModel.message = n.getStringValue(); },
        "ResultType": n => { resultTypeKeyValueModelListResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param StringResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStringResultModel(stringResultModel: Partial<StringResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { stringResultModel.data = n.getStringValue(); },
        "Message": n => { stringResultModel.message = n.getStringValue(); },
        "ResultType": n => { stringResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UserDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUserDTO(userDTO: Partial<UserDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Account": n => { userDTO.account = n.getStringValue(); },
        "CreateTime": n => { userDTO.createTime = n.getDateValue(); },
        "ID": n => { userDTO.iD = n.getGuidValue(); },
        "Name": n => { userDTO.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UserDTOResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUserDTOResultModel(userDTOResultModel: Partial<UserDTOResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { userDTOResultModel.data = n.getObjectValue<UserDTO>(createUserDTOFromDiscriminatorValue); },
        "Message": n => { userDTOResultModel.message = n.getStringValue(); },
        "ResultType": n => { userDTOResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UserListDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUserListDTO(userListDTO: Partial<UserListDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Account": n => { userListDTO.account = n.getStringValue(); },
        "CreateTime": n => { userListDTO.createTime = n.getDateValue(); },
        "ID": n => { userListDTO.iD = n.getGuidValue(); },
        "Name": n => { userListDTO.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UserListDTOCollectionResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUserListDTOCollectionResultModel(userListDTOCollectionResultModel: Partial<UserListDTOCollectionResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { userListDTOCollectionResultModel.data = n.getCollectionOfObjectValues<UserListDTO>(createUserListDTOFromDiscriminatorValue); },
        "Message": n => { userListDTOCollectionResultModel.message = n.getStringValue(); },
        "PageModel": n => { userListDTOCollectionResultModel.pageModel = n.getObjectValue<PageModel>(createPageModelFromDiscriminatorValue); },
        "RangeModel": n => { userListDTOCollectionResultModel.rangeModel = n.getObjectValue<RangeModel>(createRangeModelFromDiscriminatorValue); },
        "ResultType": n => { userListDTOCollectionResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * 命名空间修改请求模型
 */
export interface EditNamespaceRequestModel extends Parsable {
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
}
/**
 * 项目修改请求模型
 */
export interface EditProjectRequestModel extends Parsable {
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
}
/**
 * 用户修改请求模型
 */
export interface EditUserRequestModel extends Parsable {
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 姓名
     */
    name?: string | null;
}
/**
 * 配置环境数据传输模型
 */
export interface EnvironmentServerListDTO extends Parsable {
    /**
     * 主机
     */
    host?: string | null;
    /**
     * 名称
     */
    name?: string | null;
    /**
     * 端口
     */
    port?: number | null;
}
export interface EnvironmentServerListDTOListResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: EnvironmentServerListDTO[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
export interface GuidResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: Guid | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * 登录请求模型
 */
export interface LoginRequestModel extends Parsable {
    /**
     * 账号
     */
    account?: string | null;
    /**
     * 密码
     */
    password?: string | null;
}
/**
 * Token返回数据传输模型
 */
export interface LoginResultDTO extends Parsable {
    /**
     * 有效时间
     */
    expiredTime?: number | null;
    /**
     * Token
     */
    token?: string | null;
}
export interface LoginResultDTOResultModel extends Parsable {
    /**
     * Token返回数据传输模型
     */
    data?: LoginResultDTO | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * 命名空间数据传输模型
 */
export interface NamespaceDTO extends Parsable {
    /**
     * 创建时间
     */
    createTime?: Date | null;
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 名称
     */
    name?: string | null;
    /**
     * 命名空间唯一标识
     */
    projectID?: Guid | null;
}
export interface NamespaceDTOResultModel extends Parsable {
    /**
     * 命名空间数据传输模型
     */
    data?: NamespaceDTO | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * 命名空间列表数据传输模型
 */
export interface NamespaceListDTO extends Parsable {
    /**
     * 创建时间
     */
    createTime?: Date | null;
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 名称
     */
    name?: string | null;
    /**
     * 命名空间唯一标识
     */
    projectID?: Guid | null;
}
export interface NamespaceListDTOCollectionResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: NamespaceListDTO[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The PageModel property
     */
    pageModel?: PageModel | null;
    /**
     * The RangeModel property
     */
    rangeModel?: RangeModel | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
export interface PageModel extends Parsable {
    /**
     * The DataCount property
     */
    dataCount?: number | null;
    /**
     * The IsAsc property
     */
    isAsc?: boolean | null;
    /**
     * The PageCount property
     */
    pageCount?: number | null;
    /**
     * The PageIndex property
     */
    pageIndex?: number | null;
    /**
     * The PageSize property
     */
    pageSize?: number | null;
    /**
     * The Skip property
     */
    skip?: number | null;
    /**
     * The SortPropertyName property
     */
    sortPropertyName?: string | null;
    /**
     * The StartIndex property
     */
    startIndex?: number | null;
    /**
     * The Take property
     */
    take?: number | null;
}
/**
 * 项目数据传输模型
 */
export interface ProjectDTO extends Parsable {
    /**
     * 创建时间
     */
    createTime?: Date | null;
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 名称
     */
    name?: string | null;
}
export interface ProjectDTOResultModel extends Parsable {
    /**
     * 项目数据传输模型
     */
    data?: ProjectDTO | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * 项目列表数据传输模型
 */
export interface ProjectListDTO extends Parsable {
    /**
     * 创建时间
     */
    createTime?: Date | null;
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 名称
     */
    name?: string | null;
}
export interface ProjectListDTOCollectionResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: ProjectListDTO[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The PageModel property
     */
    pageModel?: PageModel | null;
    /**
     * The RangeModel property
     */
    rangeModel?: RangeModel | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * 命名空间查询请求模型
 */
export interface QueryNamespaceRequestModel extends Parsable {
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 唯一标识组
     */
    iDs?: Guid[] | null;
    /**
     * The IsAsc property
     */
    isAsc?: boolean | null;
    /**
     * 最大创建时间
     */
    maxCreateTime?: Date | null;
    /**
     * 最小创建时间
     */
    minCreateTime?: Date | null;
    /**
     * 名称
     */
    name?: string | null;
    /**
     * The PageIndex property
     */
    pageIndex?: number | null;
    /**
     * The PageSize property
     */
    pageSize?: number | null;
    /**
     * 命名空间唯一标识
     */
    projectID?: Guid | null;
    /**
     * The Skip property
     */
    skip?: number | null;
    /**
     * The SortPropertyName property
     */
    sortPropertyName?: string | null;
    /**
     * The Take property
     */
    take?: number | null;
}
/**
 * 项目查询请求模型
 */
export interface QueryProjectRequestModel extends Parsable {
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 唯一标识组
     */
    iDs?: Guid[] | null;
    /**
     * The IsAsc property
     */
    isAsc?: boolean | null;
    /**
     * 最大创建时间
     */
    maxCreateTime?: Date | null;
    /**
     * 最小创建时间
     */
    minCreateTime?: Date | null;
    /**
     * 名称
     */
    name?: string | null;
    /**
     * The PageIndex property
     */
    pageIndex?: number | null;
    /**
     * The PageSize property
     */
    pageSize?: number | null;
    /**
     * The Skip property
     */
    skip?: number | null;
    /**
     * The SortPropertyName property
     */
    sortPropertyName?: string | null;
    /**
     * The Take property
     */
    take?: number | null;
}
/**
 * 用户查询请求模型
 */
export interface QueryUserRequestModel extends Parsable {
    /**
     * 账号
     */
    account?: string | null;
    /**
     * 唯一标识组
     */
    iDs?: Guid[] | null;
    /**
     * The IsAsc property
     */
    isAsc?: boolean | null;
    /**
     * 最大创建时间
     */
    maxCreateTime?: Date | null;
    /**
     * 最小创建时间
     */
    minCreateTime?: Date | null;
    /**
     * 姓名
     */
    name?: string | null;
    /**
     * The PageIndex property
     */
    pageIndex?: number | null;
    /**
     * The PageSize property
     */
    pageSize?: number | null;
    /**
     * The Skip property
     */
    skip?: number | null;
    /**
     * The SortPropertyName property
     */
    sortPropertyName?: string | null;
    /**
     * The Take property
     */
    take?: number | null;
}
export interface RangeModel extends Parsable {
    /**
     * The DataCount property
     */
    dataCount?: number | null;
    /**
     * The IsAsc property
     */
    isAsc?: boolean | null;
    /**
     * The Skip property
     */
    skip?: number | null;
    /**
     * The SortPropertyName property
     */
    sortPropertyName?: string | null;
    /**
     * The Take property
     */
    take?: number | null;
}
export interface ResultModel extends Parsable {
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
export interface ResultTypeKeyValueModel extends Parsable {
    /**
     * The Key property
     */
    key?: number | null;
    /**
     * The Value property
     */
    value?: string | null;
}
export interface ResultTypeKeyValueModelListResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: ResultTypeKeyValueModel[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * Serializes information the current object
 * @param AddNamespaceRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAddNamespaceRequestModel(writer: SerializationWriter, addNamespaceRequestModel: Partial<AddNamespaceRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!addNamespaceRequestModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Description", addNamespaceRequestModel.description);
    writer.writeStringValue("Name", addNamespaceRequestModel.name);
    writer.writeGuidValue("ProjectID", addNamespaceRequestModel.projectID);
}
/**
 * Serializes information the current object
 * @param AddProjectRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAddProjectRequestModel(writer: SerializationWriter, addProjectRequestModel: Partial<AddProjectRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!addProjectRequestModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Description", addProjectRequestModel.description);
    writer.writeStringValue("Name", addProjectRequestModel.name);
}
/**
 * Serializes information the current object
 * @param AddUserRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAddUserRequestModel(writer: SerializationWriter, addUserRequestModel: Partial<AddUserRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!addUserRequestModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Account", addUserRequestModel.account);
    writer.writeStringValue("Name", addUserRequestModel.name);
}
/**
 * Serializes information the current object
 * @param ChangePasswordRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeChangePasswordRequestModel(writer: SerializationWriter, changePasswordRequestModel: Partial<ChangePasswordRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!changePasswordRequestModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("NewPassword", changePasswordRequestModel.newPassword);
    writer.writeStringValue("OldPassword", changePasswordRequestModel.oldPassword);
}
/**
 * Serializes information the current object
 * @param DeployListDTO The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDeployListDTO(writer: SerializationWriter, deployListDTO: Partial<DeployListDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!deployListDTO || isSerializingDerivedType) { return; }
    writer.writeStringValue("AccessUrl", deployListDTO.accessUrl);
    writer.writeStringValue("Host", deployListDTO.host);
    writer.writeStringValue("Name", deployListDTO.name);
    writer.writeNumberValue("Port", deployListDTO.port);
}
/**
 * Serializes information the current object
 * @param DeployListDTOListResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDeployListDTOListResultModel(writer: SerializationWriter, deployListDTOListResultModel: Partial<DeployListDTOListResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!deployListDTOListResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<DeployListDTO>("Data", deployListDTOListResultModel.data, serializeDeployListDTO);
    writer.writeStringValue("Message", deployListDTOListResultModel.message);
    writer.writeNumberValue("ResultType", deployListDTOListResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param EditNamespaceRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEditNamespaceRequestModel(writer: SerializationWriter, editNamespaceRequestModel: Partial<EditNamespaceRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!editNamespaceRequestModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Description", editNamespaceRequestModel.description);
    writer.writeGuidValue("ID", editNamespaceRequestModel.iD);
}
/**
 * Serializes information the current object
 * @param EditProjectRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEditProjectRequestModel(writer: SerializationWriter, editProjectRequestModel: Partial<EditProjectRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!editProjectRequestModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Description", editProjectRequestModel.description);
    writer.writeGuidValue("ID", editProjectRequestModel.iD);
}
/**
 * Serializes information the current object
 * @param EditUserRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEditUserRequestModel(writer: SerializationWriter, editUserRequestModel: Partial<EditUserRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!editUserRequestModel || isSerializingDerivedType) { return; }
    writer.writeGuidValue("ID", editUserRequestModel.iD);
    writer.writeStringValue("Name", editUserRequestModel.name);
}
/**
 * Serializes information the current object
 * @param EnvironmentServerListDTO The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEnvironmentServerListDTO(writer: SerializationWriter, environmentServerListDTO: Partial<EnvironmentServerListDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!environmentServerListDTO || isSerializingDerivedType) { return; }
    writer.writeStringValue("Host", environmentServerListDTO.host);
    writer.writeStringValue("Name", environmentServerListDTO.name);
    writer.writeNumberValue("Port", environmentServerListDTO.port);
}
/**
 * Serializes information the current object
 * @param EnvironmentServerListDTOListResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEnvironmentServerListDTOListResultModel(writer: SerializationWriter, environmentServerListDTOListResultModel: Partial<EnvironmentServerListDTOListResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!environmentServerListDTOListResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<EnvironmentServerListDTO>("Data", environmentServerListDTOListResultModel.data, serializeEnvironmentServerListDTO);
    writer.writeStringValue("Message", environmentServerListDTOListResultModel.message);
    writer.writeNumberValue("ResultType", environmentServerListDTOListResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param GuidResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGuidResultModel(writer: SerializationWriter, guidResultModel: Partial<GuidResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!guidResultModel || isSerializingDerivedType) { return; }
    writer.writeGuidValue("Data", guidResultModel.data);
    writer.writeStringValue("Message", guidResultModel.message);
    writer.writeNumberValue("ResultType", guidResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginRequestModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginRequestModel(writer: SerializationWriter, loginRequestModel: Partial<LoginRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginRequestModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Account", loginRequestModel.account);
    writer.writeStringValue("Password", loginRequestModel.password);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginResultDTO The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginResultDTO(writer: SerializationWriter, loginResultDTO: Partial<LoginResultDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginResultDTO || isSerializingDerivedType) { return; }
    writer.writeNumberValue("ExpiredTime", loginResultDTO.expiredTime);
    writer.writeStringValue("Token", loginResultDTO.token);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginResultDTOResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginResultDTOResultModel(writer: SerializationWriter, loginResultDTOResultModel: Partial<LoginResultDTOResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginResultDTOResultModel || isSerializingDerivedType) { return; }
    writer.writeObjectValue<LoginResultDTO>("Data", loginResultDTOResultModel.data, serializeLoginResultDTO);
    writer.writeStringValue("Message", loginResultDTOResultModel.message);
    writer.writeNumberValue("ResultType", loginResultDTOResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param NamespaceDTO The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeNamespaceDTO(writer: SerializationWriter, namespaceDTO: Partial<NamespaceDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!namespaceDTO || isSerializingDerivedType) { return; }
    writer.writeDateValue("CreateTime", namespaceDTO.createTime);
    writer.writeStringValue("Description", namespaceDTO.description);
    writer.writeGuidValue("ID", namespaceDTO.iD);
    writer.writeStringValue("Name", namespaceDTO.name);
    writer.writeGuidValue("ProjectID", namespaceDTO.projectID);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param NamespaceDTOResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeNamespaceDTOResultModel(writer: SerializationWriter, namespaceDTOResultModel: Partial<NamespaceDTOResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!namespaceDTOResultModel || isSerializingDerivedType) { return; }
    writer.writeObjectValue<NamespaceDTO>("Data", namespaceDTOResultModel.data, serializeNamespaceDTO);
    writer.writeStringValue("Message", namespaceDTOResultModel.message);
    writer.writeNumberValue("ResultType", namespaceDTOResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param NamespaceListDTO The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeNamespaceListDTO(writer: SerializationWriter, namespaceListDTO: Partial<NamespaceListDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!namespaceListDTO || isSerializingDerivedType) { return; }
    writer.writeDateValue("CreateTime", namespaceListDTO.createTime);
    writer.writeStringValue("Description", namespaceListDTO.description);
    writer.writeGuidValue("ID", namespaceListDTO.iD);
    writer.writeStringValue("Name", namespaceListDTO.name);
    writer.writeGuidValue("ProjectID", namespaceListDTO.projectID);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param NamespaceListDTOCollectionResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeNamespaceListDTOCollectionResultModel(writer: SerializationWriter, namespaceListDTOCollectionResultModel: Partial<NamespaceListDTOCollectionResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!namespaceListDTOCollectionResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<NamespaceListDTO>("Data", namespaceListDTOCollectionResultModel.data, serializeNamespaceListDTO);
    writer.writeStringValue("Message", namespaceListDTOCollectionResultModel.message);
    writer.writeObjectValue<PageModel>("PageModel", namespaceListDTOCollectionResultModel.pageModel, serializePageModel);
    writer.writeObjectValue<RangeModel>("RangeModel", namespaceListDTOCollectionResultModel.rangeModel, serializeRangeModel);
    writer.writeNumberValue("ResultType", namespaceListDTOCollectionResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PageModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePageModel(writer: SerializationWriter, pageModel: Partial<PageModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pageModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("DataCount", pageModel.dataCount);
    writer.writeBooleanValue("IsAsc", pageModel.isAsc);
    writer.writeNumberValue("PageIndex", pageModel.pageIndex);
    writer.writeNumberValue("PageSize", pageModel.pageSize);
    writer.writeNumberValue("Skip", pageModel.skip);
    writer.writeStringValue("SortPropertyName", pageModel.sortPropertyName);
    writer.writeNumberValue("Take", pageModel.take);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProjectDTO The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProjectDTO(writer: SerializationWriter, projectDTO: Partial<ProjectDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!projectDTO || isSerializingDerivedType) { return; }
    writer.writeDateValue("CreateTime", projectDTO.createTime);
    writer.writeStringValue("Description", projectDTO.description);
    writer.writeGuidValue("ID", projectDTO.iD);
    writer.writeStringValue("Name", projectDTO.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProjectDTOResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProjectDTOResultModel(writer: SerializationWriter, projectDTOResultModel: Partial<ProjectDTOResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!projectDTOResultModel || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ProjectDTO>("Data", projectDTOResultModel.data, serializeProjectDTO);
    writer.writeStringValue("Message", projectDTOResultModel.message);
    writer.writeNumberValue("ResultType", projectDTOResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProjectListDTO The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProjectListDTO(writer: SerializationWriter, projectListDTO: Partial<ProjectListDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!projectListDTO || isSerializingDerivedType) { return; }
    writer.writeDateValue("CreateTime", projectListDTO.createTime);
    writer.writeStringValue("Description", projectListDTO.description);
    writer.writeGuidValue("ID", projectListDTO.iD);
    writer.writeStringValue("Name", projectListDTO.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProjectListDTOCollectionResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProjectListDTOCollectionResultModel(writer: SerializationWriter, projectListDTOCollectionResultModel: Partial<ProjectListDTOCollectionResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!projectListDTOCollectionResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ProjectListDTO>("Data", projectListDTOCollectionResultModel.data, serializeProjectListDTO);
    writer.writeStringValue("Message", projectListDTOCollectionResultModel.message);
    writer.writeObjectValue<PageModel>("PageModel", projectListDTOCollectionResultModel.pageModel, serializePageModel);
    writer.writeObjectValue<RangeModel>("RangeModel", projectListDTOCollectionResultModel.rangeModel, serializeRangeModel);
    writer.writeNumberValue("ResultType", projectListDTOCollectionResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QueryNamespaceRequestModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryNamespaceRequestModel(writer: SerializationWriter, queryNamespaceRequestModel: Partial<QueryNamespaceRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!queryNamespaceRequestModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Description", queryNamespaceRequestModel.description);
    writer.writeCollectionOfPrimitiveValues<Guid>("IDs", queryNamespaceRequestModel.iDs);
    writer.writeBooleanValue("IsAsc", queryNamespaceRequestModel.isAsc);
    writer.writeDateValue("MaxCreateTime", queryNamespaceRequestModel.maxCreateTime);
    writer.writeDateValue("MinCreateTime", queryNamespaceRequestModel.minCreateTime);
    writer.writeStringValue("Name", queryNamespaceRequestModel.name);
    writer.writeNumberValue("PageIndex", queryNamespaceRequestModel.pageIndex);
    writer.writeNumberValue("PageSize", queryNamespaceRequestModel.pageSize);
    writer.writeGuidValue("ProjectID", queryNamespaceRequestModel.projectID);
    writer.writeNumberValue("Skip", queryNamespaceRequestModel.skip);
    writer.writeStringValue("SortPropertyName", queryNamespaceRequestModel.sortPropertyName);
    writer.writeNumberValue("Take", queryNamespaceRequestModel.take);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QueryProjectRequestModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryProjectRequestModel(writer: SerializationWriter, queryProjectRequestModel: Partial<QueryProjectRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!queryProjectRequestModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Description", queryProjectRequestModel.description);
    writer.writeCollectionOfPrimitiveValues<Guid>("IDs", queryProjectRequestModel.iDs);
    writer.writeBooleanValue("IsAsc", queryProjectRequestModel.isAsc);
    writer.writeDateValue("MaxCreateTime", queryProjectRequestModel.maxCreateTime);
    writer.writeDateValue("MinCreateTime", queryProjectRequestModel.minCreateTime);
    writer.writeStringValue("Name", queryProjectRequestModel.name);
    writer.writeNumberValue("PageIndex", queryProjectRequestModel.pageIndex);
    writer.writeNumberValue("PageSize", queryProjectRequestModel.pageSize);
    writer.writeNumberValue("Skip", queryProjectRequestModel.skip);
    writer.writeStringValue("SortPropertyName", queryProjectRequestModel.sortPropertyName);
    writer.writeNumberValue("Take", queryProjectRequestModel.take);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QueryUserRequestModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryUserRequestModel(writer: SerializationWriter, queryUserRequestModel: Partial<QueryUserRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!queryUserRequestModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Account", queryUserRequestModel.account);
    writer.writeCollectionOfPrimitiveValues<Guid>("IDs", queryUserRequestModel.iDs);
    writer.writeBooleanValue("IsAsc", queryUserRequestModel.isAsc);
    writer.writeDateValue("MaxCreateTime", queryUserRequestModel.maxCreateTime);
    writer.writeDateValue("MinCreateTime", queryUserRequestModel.minCreateTime);
    writer.writeStringValue("Name", queryUserRequestModel.name);
    writer.writeNumberValue("PageIndex", queryUserRequestModel.pageIndex);
    writer.writeNumberValue("PageSize", queryUserRequestModel.pageSize);
    writer.writeNumberValue("Skip", queryUserRequestModel.skip);
    writer.writeStringValue("SortPropertyName", queryUserRequestModel.sortPropertyName);
    writer.writeNumberValue("Take", queryUserRequestModel.take);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RangeModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRangeModel(writer: SerializationWriter, rangeModel: Partial<RangeModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!rangeModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("DataCount", rangeModel.dataCount);
    writer.writeBooleanValue("IsAsc", rangeModel.isAsc);
    writer.writeNumberValue("Skip", rangeModel.skip);
    writer.writeStringValue("SortPropertyName", rangeModel.sortPropertyName);
    writer.writeNumberValue("Take", rangeModel.take);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResultModel(writer: SerializationWriter, resultModel: Partial<ResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!resultModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Message", resultModel.message);
    writer.writeNumberValue("ResultType", resultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResultTypeKeyValueModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResultTypeKeyValueModel(writer: SerializationWriter, resultTypeKeyValueModel: Partial<ResultTypeKeyValueModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!resultTypeKeyValueModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("Key", resultTypeKeyValueModel.key);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResultTypeKeyValueModelListResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResultTypeKeyValueModelListResultModel(writer: SerializationWriter, resultTypeKeyValueModelListResultModel: Partial<ResultTypeKeyValueModelListResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!resultTypeKeyValueModelListResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ResultTypeKeyValueModel>("Data", resultTypeKeyValueModelListResultModel.data, serializeResultTypeKeyValueModel);
    writer.writeStringValue("Message", resultTypeKeyValueModelListResultModel.message);
    writer.writeNumberValue("ResultType", resultTypeKeyValueModelListResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param StringResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStringResultModel(writer: SerializationWriter, stringResultModel: Partial<StringResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!stringResultModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Data", stringResultModel.data);
    writer.writeStringValue("Message", stringResultModel.message);
    writer.writeNumberValue("ResultType", stringResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UserDTO The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUserDTO(writer: SerializationWriter, userDTO: Partial<UserDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!userDTO || isSerializingDerivedType) { return; }
    writer.writeStringValue("Account", userDTO.account);
    writer.writeDateValue("CreateTime", userDTO.createTime);
    writer.writeGuidValue("ID", userDTO.iD);
    writer.writeStringValue("Name", userDTO.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UserDTOResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUserDTOResultModel(writer: SerializationWriter, userDTOResultModel: Partial<UserDTOResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!userDTOResultModel || isSerializingDerivedType) { return; }
    writer.writeObjectValue<UserDTO>("Data", userDTOResultModel.data, serializeUserDTO);
    writer.writeStringValue("Message", userDTOResultModel.message);
    writer.writeNumberValue("ResultType", userDTOResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UserListDTO The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUserListDTO(writer: SerializationWriter, userListDTO: Partial<UserListDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!userListDTO || isSerializingDerivedType) { return; }
    writer.writeStringValue("Account", userListDTO.account);
    writer.writeDateValue("CreateTime", userListDTO.createTime);
    writer.writeGuidValue("ID", userListDTO.iD);
    writer.writeStringValue("Name", userListDTO.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UserListDTOCollectionResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUserListDTOCollectionResultModel(writer: SerializationWriter, userListDTOCollectionResultModel: Partial<UserListDTOCollectionResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!userListDTOCollectionResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<UserListDTO>("Data", userListDTOCollectionResultModel.data, serializeUserListDTO);
    writer.writeStringValue("Message", userListDTOCollectionResultModel.message);
    writer.writeObjectValue<PageModel>("PageModel", userListDTOCollectionResultModel.pageModel, serializePageModel);
    writer.writeObjectValue<RangeModel>("RangeModel", userListDTOCollectionResultModel.rangeModel, serializeRangeModel);
    writer.writeNumberValue("ResultType", userListDTOCollectionResultModel.resultType);
}
export interface StringResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: string | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * 用户数据传输模型
 */
export interface UserDTO extends Parsable {
    /**
     * 账号
     */
    account?: string | null;
    /**
     * 创建时间
     */
    createTime?: Date | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 姓名
     */
    name?: string | null;
}
export interface UserDTOResultModel extends Parsable {
    /**
     * 用户数据传输模型
     */
    data?: UserDTO | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * 用户列表数据传输模型
 */
export interface UserListDTO extends Parsable {
    /**
     * 账号
     */
    account?: string | null;
    /**
     * 创建时间
     */
    createTime?: Date | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 姓名
     */
    name?: string | null;
}
export interface UserListDTOCollectionResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: UserListDTO[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The PageModel property
     */
    pageModel?: PageModel | null;
    /**
     * The RangeModel property
     */
    rangeModel?: RangeModel | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/* tslint:enable */
/* eslint-enable */
