/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.EnumControllerGeneratorCodePlug.AfterExcuteAsync */

using Microsoft.AspNetCore.Authorization;
using Materal.Utils.Enums;

namespace MateralReleaseCenter.ServerCenter.Application.Controllers;

/// <summary>
/// 枚举控制器
/// </summary>
[AllowAnonymous]
public partial class EnumsController : ServerCenterController
{

    /// <summary>
    /// 获取所有返回对象类型枚举
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public ResultModel<List<KeyValueModel<ResultType>>> GetAllResultType()
    {
        List<KeyValueModel<ResultType>> result = KeyValueModel<ResultType>.GetAllCode();
        return ResultModel<List<KeyValueModel<ResultType>>>.Success(result, "获取成功");
    }
}
