/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorControllersCodeAsync>d__7.MoveNext */

using MateralReleaseCenter.ServerCenter.Abstractions.DTO.Namespace;
using MateralReleaseCenter.ServerCenter.Abstractions.RequestModel.Namespace;
using MateralReleaseCenter.ServerCenter.Abstractions.Services.Models.Namespace;

namespace MateralReleaseCenter.ServerCenter.Application.Controllers;

/// <summary>
/// 命名空间控制器
/// </summary>

public partial class NamespaceController : ServerCenterController<AddNamespaceRequestModel, EditNamespaceRequestModel, QueryNamespaceRequestModel, AddNamespaceModel, EditNamespaceModel, QueryNamespaceModel, NamespaceDTO, NamespaceListDTO, INamespaceService>, INamespaceController
{
}
