/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorControllersCodeAsync>d__7.MoveNext */

using MateralReleaseCenter.ServerCenter.Abstractions.DTO.Project;
using MateralReleaseCenter.ServerCenter.Abstractions.RequestModel.Project;
using MateralReleaseCenter.ServerCenter.Abstractions.Services.Models.Project;

namespace MateralReleaseCenter.ServerCenter.Application.Controllers;

/// <summary>
/// 项目控制器
/// </summary>

public partial class ProjectController : ServerCenterController<AddProjectRequestModel, EditProjectRequestModel, QueryProjectRequestModel, AddProjectModel, EditProjectModel, QueryProjectModel, ProjectDTO, ProjectListDTO, IProjectService>, IProjectController
{
}
