/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFileInfoDTOListResultModelFromDiscriminatorValue, type FileInfoDTOListResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/GetUploadFiles
 */
export interface GetUploadFilesRequestBuilder extends BaseRequestBuilder<GetUploadFilesRequestBuilder> {
    /**
     * 获得上传文件列表
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FileInfoDTOListResultModel>}
     */
     get(requestConfiguration?: RequestConfiguration<GetUploadFilesRequestBuilderGetQueryParameters> | undefined) : Promise<FileInfoDTOListResultModel | undefined>;
    /**
     * 获得上传文件列表
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<GetUploadFilesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * 获得上传文件列表
 */
export interface GetUploadFilesRequestBuilderGetQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const GetUploadFilesRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/GetUploadFiles{?id*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetUploadFilesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetUploadFilesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createFileInfoDTOListResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
