/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createInt32ResultModelFromDiscriminatorValue, type Int32ResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/GetMaxConsoleMessageCount
 */
export interface GetMaxConsoleMessageCountRequestBuilder extends BaseRequestBuilder<GetMaxConsoleMessageCountRequestBuilder> {
    /**
     * 获得控制台消息数量
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Int32ResultModel>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Int32ResultModel | undefined>;
    /**
     * 获得控制台消息数量
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetMaxConsoleMessageCountRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/GetMaxConsoleMessageCount";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetMaxConsoleMessageCountRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetMaxConsoleMessageCountRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createInt32ResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
