/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AddRequestBuilderRequestsMetadata, type AddRequestBuilder } from './add/index.js';
// @ts-ignore
import { ApplyFileRequestBuilderRequestsMetadata, type ApplyFileRequestBuilder } from './applyFile/index.js';
// @ts-ignore
import { ApplyLasetFileRequestBuilderRequestsMetadata, type ApplyLasetFileRequestBuilder } from './applyLasetFile/index.js';
// @ts-ignore
import { ClearConsoleMessagesRequestBuilderRequestsMetadata, type ClearConsoleMessagesRequestBuilder } from './clearConsoleMessages/index.js';
// @ts-ignore
import { DeleteRequestBuilderRequestsMetadata, type DeleteRequestBuilder } from './delete/index.js';
// @ts-ignore
import { DeleteFileRequestBuilderRequestsMetadata, type DeleteFileRequestBuilder } from './deleteFile/index.js';
// @ts-ignore
import { EditRequestBuilderRequestsMetadata, type EditRequestBuilder } from './edit/index.js';
// @ts-ignore
import { GetConsoleMessagesRequestBuilderRequestsMetadata, type GetConsoleMessagesRequestBuilder } from './getConsoleMessages/index.js';
// @ts-ignore
import { GetInfoRequestBuilderRequestsMetadata, type GetInfoRequestBuilder } from './getInfo/index.js';
// @ts-ignore
import { GetListRequestBuilderRequestsMetadata, type GetListRequestBuilder } from './getList/index.js';
// @ts-ignore
import { GetMaxConsoleMessageCountRequestBuilderRequestsMetadata, type GetMaxConsoleMessageCountRequestBuilder } from './getMaxConsoleMessageCount/index.js';
// @ts-ignore
import { GetUploadFilesRequestBuilderRequestsMetadata, type GetUploadFilesRequestBuilder } from './getUploadFiles/index.js';
// @ts-ignore
import { KillRequestBuilderRequestsMetadata, type KillRequestBuilder } from './kill/index.js';
// @ts-ignore
import { StartRequestBuilderRequestsMetadata, type StartRequestBuilder } from './start/index.js';
// @ts-ignore
import { StartAllRequestBuilderRequestsMetadata, type StartAllRequestBuilder } from './startAll/index.js';
// @ts-ignore
import { StopRequestBuilderRequestsMetadata, type StopRequestBuilder } from './stop/index.js';
// @ts-ignore
import { StopAllRequestBuilderRequestsMetadata, type StopAllRequestBuilder } from './stopAll/index.js';
// @ts-ignore
import { type UploadNewFileRequestBuilder, UploadNewFileRequestBuilderRequestsMetadata } from './uploadNewFile/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo
 */
export interface ApplicationInfoRequestBuilder extends BaseRequestBuilder<ApplicationInfoRequestBuilder> {
    /**
     * The Add property
     */
    get add(): AddRequestBuilder;
    /**
     * The ApplyFile property
     */
    get applyFile(): ApplyFileRequestBuilder;
    /**
     * The ApplyLasetFile property
     */
    get applyLasetFile(): ApplyLasetFileRequestBuilder;
    /**
     * The ClearConsoleMessages property
     */
    get clearConsoleMessages(): ClearConsoleMessagesRequestBuilder;
    /**
     * The DeleteFile property
     */
    get deleteFile(): DeleteFileRequestBuilder;
    /**
     * The DeletePath property
     */
    get deletePath(): DeleteRequestBuilder;
    /**
     * The Edit property
     */
    get edit(): EditRequestBuilder;
    /**
     * The GetConsoleMessages property
     */
    get getConsoleMessages(): GetConsoleMessagesRequestBuilder;
    /**
     * The GetInfo property
     */
    get getInfo(): GetInfoRequestBuilder;
    /**
     * The GetList property
     */
    get getList(): GetListRequestBuilder;
    /**
     * The GetMaxConsoleMessageCount property
     */
    get getMaxConsoleMessageCount(): GetMaxConsoleMessageCountRequestBuilder;
    /**
     * The GetUploadFiles property
     */
    get getUploadFiles(): GetUploadFilesRequestBuilder;
    /**
     * The Kill property
     */
    get kill(): KillRequestBuilder;
    /**
     * The Start property
     */
    get start(): StartRequestBuilder;
    /**
     * The StartAll property
     */
    get startAll(): StartAllRequestBuilder;
    /**
     * The Stop property
     */
    get stop(): StopRequestBuilder;
    /**
     * The StopAll property
     */
    get stopAll(): StopAllRequestBuilder;
    /**
     * The UploadNewFile property
     */
    get uploadNewFile(): UploadNewFileRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApplicationInfoRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApplicationInfoRequestBuilderNavigationMetadata: Record<Exclude<keyof ApplicationInfoRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    add: {
        requestsMetadata: AddRequestBuilderRequestsMetadata,
    },
    applyFile: {
        requestsMetadata: ApplyFileRequestBuilderRequestsMetadata,
    },
    applyLasetFile: {
        requestsMetadata: ApplyLasetFileRequestBuilderRequestsMetadata,
    },
    clearConsoleMessages: {
        requestsMetadata: ClearConsoleMessagesRequestBuilderRequestsMetadata,
    },
    deleteFile: {
        requestsMetadata: DeleteFileRequestBuilderRequestsMetadata,
    },
    deletePath: {
        requestsMetadata: DeleteRequestBuilderRequestsMetadata,
    },
    edit: {
        requestsMetadata: EditRequestBuilderRequestsMetadata,
    },
    getConsoleMessages: {
        requestsMetadata: GetConsoleMessagesRequestBuilderRequestsMetadata,
    },
    getInfo: {
        requestsMetadata: GetInfoRequestBuilderRequestsMetadata,
    },
    getList: {
        requestsMetadata: GetListRequestBuilderRequestsMetadata,
    },
    getMaxConsoleMessageCount: {
        requestsMetadata: GetMaxConsoleMessageCountRequestBuilderRequestsMetadata,
    },
    getUploadFiles: {
        requestsMetadata: GetUploadFilesRequestBuilderRequestsMetadata,
    },
    kill: {
        requestsMetadata: KillRequestBuilderRequestsMetadata,
    },
    start: {
        requestsMetadata: StartRequestBuilderRequestsMetadata,
    },
    startAll: {
        requestsMetadata: StartAllRequestBuilderRequestsMetadata,
    },
    stop: {
        requestsMetadata: StopRequestBuilderRequestsMetadata,
    },
    stopAll: {
        requestsMetadata: StopAllRequestBuilderRequestsMetadata,
    },
    uploadNewFile: {
        requestsMetadata: UploadNewFileRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
