/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDefaultDataListDTOCollectionResultModelFromDiscriminatorValue, serializeDefaultDataListDTOCollectionResultModel, serializeQueryDefaultDataRequestModel, type DefaultDataListDTOCollectionResultModel, type QueryDefaultDataRequestModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/DefaultData/GetList
 */
export interface GetListRequestBuilder extends BaseRequestBuilder<GetListRequestBuilder> {
    /**
     * @param body 默认数据查询请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DefaultDataListDTOCollectionResultModel>}
     */
     post(body: QueryDefaultDataRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DefaultDataListDTOCollectionResultModel | undefined>;
    /**
     * @param body 默认数据查询请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryDefaultDataRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetListRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/DefaultData/GetList";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: GetListRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createDefaultDataListDTOCollectionResultModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryDefaultDataRequestModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
