/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerAccessorsGeneratorCodePlug+<GeneratorControllerAccessorAsync>d__9.MoveNext */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.ApplicationInfo;
using MateralReleaseCenter.DeployServer.Abstractions.RequestModel;
using Microsoft.AspNetCore.Http;
using MateralReleaseCenter.DeployServer.Abstractions.RequestModel.ApplicationInfo;

namespace MateralReleaseCenter.DeployServer.Abstractions.ControllerAccessors;

/// <summary>
/// 应用程序服务控制器访问器
/// </summary>

public partial class ApplicationInfoControllerAccessor(IServiceProvider serviceProvider) : BaseControllerAccessor<IApplicationInfoController, AddApplicationInfoRequestModel, EditApplicationInfoRequestModel, QueryApplicationInfoRequestModel, ApplicationInfoDTO, ApplicationInfoListDTO>(serviceProvider), IApplicationInfoController

{
    /// <summary>
    /// 项目名称
    /// </summary>
    public override string ProjectName => "MateralReleaseCenter";
    /// <summary>
    /// 模块名称
    /// </summary>
    public override string ModuleName => "DeployServer";
    /// <summary>
    /// 应用最后一个文件
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public ResultModel ApplyLasetFile(Guid id)
        => HttpHelper.SendAsync<IApplicationInfoController, ResultModel>(ProjectName, ModuleName, nameof(ApplyLasetFile), []).Result;
    /// <summary>
    /// 应用文件
    /// </summary>
    /// <param name="id"></param>
    /// <param name="fileName"></param>
    /// <returns></returns>
    public ResultModel ApplyFile(Guid id, string fileName)
        => HttpHelper.SendAsync<IApplicationInfoController, ResultModel>(ProjectName, ModuleName, nameof(ApplyFile), []).Result;
    /// <summary>
    /// 删除文件
    /// </summary>
    /// <param name="id"></param>
    /// <param name="fileName"></param>
    /// <returns></returns>
    public ResultModel DeleteFile(Guid id, string fileName)
        => HttpHelper.SendAsync<IApplicationInfoController, ResultModel>(ProjectName, ModuleName, nameof(DeleteFile), []).Result;
    /// <summary>
    /// 启动程序
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public ResultModel Start(Guid id)
        => HttpHelper.SendAsync<IApplicationInfoController, ResultModel>(ProjectName, ModuleName, nameof(Start), []).Result;
    /// <summary>
    /// 停止程序
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public ResultModel Stop(Guid id)
        => HttpHelper.SendAsync<IApplicationInfoController, ResultModel>(ProjectName, ModuleName, nameof(Stop), []).Result;
    /// <summary>
    /// 杀死程序
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public async Task<ResultModel> KillAsync(Guid id)
        => await HttpHelper.SendAsync<IApplicationInfoController, ResultModel>(ProjectName, ModuleName, nameof(KillAsync), []);
    /// <summary>
    /// 全部启动
    /// </summary>
    /// <returns></returns>
    public ResultModel StartAll()
        => HttpHelper.SendAsync<IApplicationInfoController, ResultModel>(ProjectName, ModuleName, nameof(StartAll), []).Result;
    /// <summary>
    /// 全部停止
    /// </summary>
    /// <returns></returns>
    public ResultModel StopAll()
        => HttpHelper.SendAsync<IApplicationInfoController, ResultModel>(ProjectName, ModuleName, nameof(StopAll), []).Result;
    /// <summary>
    /// 获得控制台信息
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public ResultModel<ICollection<string>> GetConsoleMessages(Guid id)
        => HttpHelper.SendAsync<IApplicationInfoController, ResultModel<ICollection<string>>>(ProjectName, ModuleName, nameof(GetConsoleMessages), []).Result;
    /// <summary>
    /// 清空控制台信息
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public ResultModel ClearConsoleMessages(Guid id)
        => HttpHelper.SendAsync<IApplicationInfoController, ResultModel>(ProjectName, ModuleName, nameof(ClearConsoleMessages), []).Result;
    /// <summary>
    /// 获得上传文件列表
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public ResultModel<List<FileInfoDTO>> GetUploadFiles(Guid id)
        => HttpHelper.SendAsync<IApplicationInfoController, ResultModel<List<FileInfoDTO>>>(ProjectName, ModuleName, nameof(GetUploadFiles), []).Result;
    /// <summary>
    /// 上传新文件
    /// </summary>
    /// <param name="id"></param>
    /// <param name="file"></param>
    /// <returns></returns>
    public async Task<ResultModel> UploadNewFileAsync(Guid id, IFormFile file)
        => await HttpHelper.SendAsync<IApplicationInfoController, ResultModel>(ProjectName, ModuleName, nameof(UploadNewFileAsync), []);
    /// <summary>
    /// 获得控制台消息数量
    /// </summary>
    /// <returns></returns>
    public ResultModel<int> GetMaxConsoleMessageCount()
        => HttpHelper.SendAsync<IApplicationInfoController, ResultModel<int>>(ProjectName, ModuleName, nameof(GetMaxConsoleMessageCount), []).Result;
}