/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerAccessorsGeneratorCodePlug+<GeneratorControllerAccessorAsync>d__9.MoveNext */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalEnvironment;
using MateralReleaseCenter.DeployServer.Abstractions.RequestModel.GlobalEnvironment;

namespace MateralReleaseCenter.DeployServer.Abstractions.ControllerAccessors;

/// <summary>
/// 全局环境变量控制器访问器
/// </summary>

public partial class GlobalEnvironmentControllerAccessor(IServiceProvider serviceProvider) : BaseControllerAccessor<IGlobalEnvironmentController, AddGlobalEnvironmentRequestModel, EditGlobalEnvironmentRequestModel, QueryGlobalEnvironmentRequestModel, GlobalEnvironmentDTO, GlobalEnvironmentListDTO>(serviceProvider), IGlobalEnvironmentController

{
    /// <summary>
    /// 项目名称
    /// </summary>
    public override string ProjectName => "MateralReleaseCenter";
    /// <summary>
    /// 模块名称
    /// </summary>
    public override string ModuleName => "DeployServer";
}