/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerAccessorsGeneratorCodePlug+<GeneratorControllerAccessorAsync>d__9.MoveNext */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalParameter;
using MateralReleaseCenter.DeployServer.Abstractions.RequestModel.GlobalParameter;

namespace MateralReleaseCenter.DeployServer.Abstractions.ControllerAccessors;

/// <summary>
/// 全局参数控制器访问器
/// </summary>

public partial class GlobalParameterControllerAccessor(IServiceProvider serviceProvider) : BaseControllerAccessor<IGlobalParameterController, AddGlobalParameterRequestModel, EditGlobalParameterRequestModel, QueryGlobalParameterRequestModel, GlobalParameterDTO, GlobalParameterListDTO>(serviceProvider), IGlobalParameterController

{
    /// <summary>
    /// 项目名称
    /// </summary>
    public override string ProjectName => "MateralReleaseCenter";
    /// <summary>
    /// 模块名称
    /// </summary>
    public override string ModuleName => "DeployServer";
}