/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerAccessorsGeneratorCodePlug+<GeneratorControllerAccessorServiceCollectionExtensionsAsync>d__10.MoveNext */

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace MateralReleaseCenter.DeployServer.Abstractions.ControllerAccessors
{
    /// <summary>
    /// 服务集合扩展
    /// </summary>
    public static class ServiceCollectionExtensions
    {
        /// <summary>
        /// 添加控制器访问器
        /// </summary>
        /// <param name="services"></param>
        public static void AddDeployServerControllerAccessors(this IServiceCollection services)
        {
            services.TryAddSingleton<IApplicationInfoController, ApplicationInfoControllerAccessor>();
            services.TryAddSingleton<IGlobalEnvironmentController, GlobalEnvironmentControllerAccessor>();
            services.TryAddSingleton<IGlobalParameterController, GlobalParameterControllerAccessor>();
        }
    }
}