/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorDBContextCodeAsync>d__10.MoveNext */

namespace MateralReleaseCenter.DeployServer.Repository;
/// <summary>
/// DeployServer数据库上下文
/// </summary>
public sealed partial class DeployServerDBContext(DbContextOptions<DeployServerDBContext> options) : DbContext(options)
{
    /// <summary>
    /// 应用程序信息
    /// </summary>
    public DbSet<ApplicationInfo>? ApplicationInfo { get; set; }
    /// <summary>
    /// 默认数据
    /// </summary>
    public DbSet<DefaultData>? DefaultData { get; set; }
    /// <summary>
    /// 配置模型
    /// </summary>
    protected override void OnModelCreating(ModelBuilder modelBuilder) => modelBuilder.ApplyConfigurationsFromAssembly(GetType().Assembly);
}
