/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createStringResultModelFromDiscriminatorValue, type StringResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/User/ResetPassword
 */
export interface ResetPasswordRequestBuilder extends BaseRequestBuilder<ResetPasswordRequestBuilder> {
    /**
     * 重置密码
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<StringResultModel>}
     */
     put(requestConfiguration?: RequestConfiguration<ResetPasswordRequestBuilderPutQueryParameters> | undefined) : Promise<StringResultModel | undefined>;
    /**
     * 重置密码
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(requestConfiguration?: RequestConfiguration<ResetPasswordRequestBuilderPutQueryParameters> | undefined) : RequestInformation;
}
/**
 * 重置密码
 */
export interface ResetPasswordRequestBuilderPutQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const ResetPasswordRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/User/ResetPassword{?id*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ResetPasswordRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: ResetPasswordRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createStringResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
