/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, type ResultModel } from '../../../models/index.js';
// @ts-ignore
import { MultipartBody, serializeMultipartBody, type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/UploadNewFile
 */
export interface UploadNewFileRequestBuilder extends BaseRequestBuilder<UploadNewFileRequestBuilder> {
    /**
     * 上传新文件
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     put(body: MultipartBody, requestConfiguration?: RequestConfiguration<UploadNewFileRequestBuilderPutQueryParameters> | undefined) : Promise<ResultModel | undefined>;
    /**
     * 上传新文件
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: MultipartBody, requestConfiguration?: RequestConfiguration<UploadNewFileRequestBuilderPutQueryParameters> | undefined) : RequestInformation;
}
/**
 * 上传新文件
 */
export interface UploadNewFileRequestBuilderPutQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const UploadNewFileRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/UploadNewFile?id={id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const UploadNewFileRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: UploadNewFileRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
        requestBodyContentType: "multipart/form-data",
        requestBodySerializer: serializeMultipartBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
