/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApplicationStatusEnumKeyValueModelListResultModelFromDiscriminatorValue, type ApplicationStatusEnumKeyValueModelListResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/Enums/GetAllApplicationStatusEnum
 */
export interface GetAllApplicationStatusEnumRequestBuilder extends BaseRequestBuilder<GetAllApplicationStatusEnumRequestBuilder> {
    /**
     * 获取所有应用程序状态枚举
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ApplicationStatusEnumKeyValueModelListResultModel>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ApplicationStatusEnumKeyValueModelListResultModel | undefined>;
    /**
     * 获取所有应用程序状态枚举
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetAllApplicationStatusEnumRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/Enums/GetAllApplicationStatusEnum";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetAllApplicationStatusEnumRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetAllApplicationStatusEnumRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createApplicationStatusEnumKeyValueModelListResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
