/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorControllersCodeAsync>d__7.MoveNext */

using MateralReleaseCenter.EnvironmentServer.Abstractions.DTO.ConfigurationItem;
using MateralReleaseCenter.EnvironmentServer.Abstractions.RequestModel.ConfigurationItem;
using MateralReleaseCenter.EnvironmentServer.Abstractions.Services.Models.ConfigurationItem;

namespace MateralReleaseCenter.EnvironmentServer.Application.Controllers;

/// <summary>
/// 配置项控制器
/// </summary>

public partial class ConfigurationItemController : EnvironmentServerController<AddConfigurationItemRequestModel, EditConfigurationItemRequestModel, QueryConfigurationItemRequestModel, AddConfigurationItemModel, EditConfigurationItemModel, QueryConfigurationItemModel, ConfigurationItemDTO, ConfigurationItemListDTO, IConfigurationItemService>, IConfigurationItemController
{
}
