/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.EnumControllerGeneratorCodePlug.AfterExcuteAsync */

using Microsoft.AspNetCore.Authorization;
using Materal.Utils.Enums;
using MateralReleaseCenter.EnvironmentServer.Abstractions.Enums;

namespace MateralReleaseCenter.EnvironmentServer.Application.Controllers;

/// <summary>
/// 枚举控制器
/// </summary>
[AllowAnonymous]
public partial class EnumsController : EnvironmentServerController
{
    /// <summary>
    /// 获取所有同步模式枚举
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public ResultModel<List<KeyValueModel<SyncModeEnum>>> GetAllSyncModeEnum()
    {
        List<KeyValueModel<SyncModeEnum>> result = KeyValueModel<SyncModeEnum>.GetAllCode();
        return ResultModel<List<KeyValueModel<SyncModeEnum>>>.Success(result, "获取成功");
    }

    /// <summary>
    /// 获取所有返回对象类型枚举
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public ResultModel<List<KeyValueModel<ResultType>>> GetAllResultType()
    {
        List<KeyValueModel<ResultType>> result = KeyValueModel<ResultType>.GetAllCode();
        return ResultModel<List<KeyValueModel<ResultType>>>.Success(result, "获取成功");
    }
}
