/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorRepositoryImplCodeAsync>d__12.MoveNext */

namespace MateralReleaseCenter.EnvironmentServer.Repository.Repositories;
/// <summary>
/// 配置项仓储
/// </summary>

public partial class ConfigurationItemRepositoryImpl(EnvironmentServerDBContext dbContext) : EnvironmentServerRepositoryImpl<ConfigurationItem>(dbContext), IConfigurationItemRepository, IScopedDependency<IConfigurationItemRepository>
{

}
