/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, serializeEditProjectRequestModel, serializeResultModel, type EditProjectRequestModel, type ResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/Project/Edit
 */
export interface EditRequestBuilder extends BaseRequestBuilder<EditRequestBuilder> {
    /**
     * @param body 项目修改请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     put(body: EditProjectRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ResultModel | undefined>;
    /**
     * @param body 项目修改请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: EditProjectRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const EditRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/Project/Edit";
/**
 * Metadata for all the requests in the request builder.
 */
export const EditRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: EditRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeEditProjectRequestModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
