/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorEntityConfigCodeAsync>d__9.MoveNext */

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MateralReleaseCenter.DeployServer.Repository.EntityConfigs;
/// <summary>
/// 应用程序信息配置基类
/// </summary>
public class ApplicationInfoConfigBase : BaseEntityConfig<ApplicationInfo>
{
    /// <summary>
    /// 配置
    /// </summary>
    public override void Configure(EntityTypeBuilder<ApplicationInfo> builder)
    {
        builder = BaseConfigure(builder);
        builder.ToTable(m => m.HasComment("应用程序信息"));
        builder.Property(e => e.Name)
            .IsRequired()
            .HasComment("名称");
        builder.Property(e => e.RootPath)
            .IsRequired()
            .HasComment("根路径");
        builder.Property(e => e.MainModule)
            .IsRequired()
            .HasComment("主模块");
        builder.Property(e => e.ApplicationType)
            .IsRequired()
            .HasComment("应用程序类型");
        builder.Property(e => e.IsIncrementalUpdating)
            .IsRequired()
            .HasComment("增量更新");
        builder.Property(e => e.RunParams)
            .HasComment("运行参数");
        builder.Property(e => e.RepositoryUrl)
            .HasComment("仓库地址");
        builder.Property(e => e.AuthToken)
            .HasComment("授权令牌");
    }
}
/// <summary>
/// 应用程序信息配置类
/// </summary>
public partial class ApplicationInfoConfig : ApplicationInfoConfigBase { }
