/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorEntityConfigCodeAsync>d__9.MoveNext */

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MateralReleaseCenter.DeployServer.Repository.EntityConfigs;
/// <summary>
/// 全局环境变量配置基类
/// </summary>
public class GlobalEnvironmentConfigBase : BaseEntityConfig<GlobalEnvironment>
{
    /// <summary>
    /// 配置
    /// </summary>
    public override void Configure(EntityTypeBuilder<GlobalEnvironment> builder)
    {
        builder = BaseConfigure(builder);
        builder.ToTable(m => m.HasComment("全局环境变量"));
        builder.Property(e => e.ApplicationType)
            .IsRequired()
            .HasComment("应用程序类型");
        builder.Property(e => e.Key)
            .IsRequired()
            .HasComment("键");
        builder.Property(e => e.Value)
            .IsRequired()
            .HasComment("值");
        builder.Property(e => e.Description)
            .HasComment("描述");
    }
}
/// <summary>
/// 全局环境变量配置类
/// </summary>
public partial class GlobalEnvironmentConfig : GlobalEnvironmentConfigBase { }
