/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorEntityConfigCodeAsync>d__9.MoveNext */

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MateralReleaseCenter.DeployServer.Repository.EntityConfigs;
/// <summary>
/// 全局参数配置基类
/// </summary>
public class GlobalParameterConfigBase : BaseEntityConfig<GlobalParameter>
{
    /// <summary>
    /// 配置
    /// </summary>
    public override void Configure(EntityTypeBuilder<GlobalParameter> builder)
    {
        builder = BaseConfigure(builder);
        builder.ToTable(m => m.HasComment("全局参数"));
        builder.Property(e => e.ApplicationType)
            .IsRequired()
            .HasComment("应用程序类型");
        builder.Property(e => e.Name)
            .IsRequired()
            .HasComment("名称");
        builder.Property(e => e.Value)
            .IsRequired()
            .HasComment("值");
    }
}
/// <summary>
/// 全局参数配置类
/// </summary>
public partial class GlobalParameterConfig : GlobalParameterConfigBase { }
