/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultTypeKeyValueModelListResultModelFromDiscriminatorValue, type ResultTypeKeyValueModelListResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/Enums/GetAllResultType
 */
export interface GetAllResultTypeRequestBuilder extends BaseRequestBuilder<GetAllResultTypeRequestBuilder> {
    /**
     * 获取所有返回对象类型枚举
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultTypeKeyValueModelListResultModel>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ResultTypeKeyValueModelListResultModel | undefined>;
    /**
     * 获取所有返回对象类型枚举
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetAllResultTypeRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/Enums/GetAllResultType";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetAllResultTypeRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetAllResultTypeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultTypeKeyValueModelListResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
