/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, type ResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/ApplyLasetFile
 */
export interface ApplyLasetFileRequestBuilder extends BaseRequestBuilder<ApplyLasetFileRequestBuilder> {
    /**
     * 应用最后一个文件
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     put(requestConfiguration?: RequestConfiguration<ApplyLasetFileRequestBuilderPutQueryParameters> | undefined) : Promise<ResultModel | undefined>;
    /**
     * 应用最后一个文件
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(requestConfiguration?: RequestConfiguration<ApplyLasetFileRequestBuilderPutQueryParameters> | undefined) : RequestInformation;
}
/**
 * 应用最后一个文件
 */
export interface ApplyLasetFileRequestBuilderPutQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const ApplyLasetFileRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/ApplyLasetFile{?id*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ApplyLasetFileRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: ApplyLasetFileRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
