/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApplicationInfoListDTOCollectionResultModelFromDiscriminatorValue, serializeApplicationInfoListDTOCollectionResultModel, serializeQueryApplicationInfoRequestModel, type ApplicationInfoListDTOCollectionResultModel, type QueryApplicationInfoRequestModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/GetList
 */
export interface GetListRequestBuilder extends BaseRequestBuilder<GetListRequestBuilder> {
    /**
     * @param body 应用程序信息查询请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ApplicationInfoListDTOCollectionResultModel>}
     */
     post(body: QueryApplicationInfoRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ApplicationInfoListDTOCollectionResultModel | undefined>;
    /**
     * @param body 应用程序信息查询请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryApplicationInfoRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetListRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/GetList";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: GetListRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createApplicationInfoListDTOCollectionResultModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryApplicationInfoRequestModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
