/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorControllersCodeAsync>d__7.MoveNext */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.DefaultData;
using MateralReleaseCenter.DeployServer.Abstractions.RequestModel.DefaultData;
using MateralReleaseCenter.DeployServer.Abstractions.Services.Models.DefaultData;

namespace MateralReleaseCenter.DeployServer.Application.Controllers;

/// <summary>
/// 默认数据控制器
/// </summary>

public partial class DefaultDataController : DeployServerController<AddDefaultDataRequestModel, EditDefaultDataRequestModel, QueryDefaultDataRequestModel, AddDefaultDataModel, EditDefaultDataModel, QueryDefaultDataModel, DefaultDataDTO, DefaultDataListDTO, IDefaultDataService>, IDefaultDataController
{
}
