/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.EnumControllerGeneratorCodePlug.AfterExcuteAsync */

using Microsoft.AspNetCore.Authorization;
using Materal.Utils.Enums;
using MateralReleaseCenter.DeployServer.Abstractions.Enums;

namespace MateralReleaseCenter.DeployServer.Application.Controllers;

/// <summary>
/// 枚举控制器
/// </summary>
[AllowAnonymous]
public partial class EnumsController : DeployServerController
{
    /// <summary>
    /// 获取所有应用程序状态枚举
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public ResultModel<List<KeyValueModel<ApplicationStatusEnum>>> GetAllApplicationStatusEnum()
    {
        List<KeyValueModel<ApplicationStatusEnum>> result = KeyValueModel<ApplicationStatusEnum>.GetAllCode();
        return ResultModel<List<KeyValueModel<ApplicationStatusEnum>>>.Success(result, "获取成功");
    }
    /// <summary>
    /// 获取所有应用程序类型枚举
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public ResultModel<List<KeyValueModel<ApplicationTypeEnum>>> GetAllApplicationTypeEnum()
    {
        List<KeyValueModel<ApplicationTypeEnum>> result = KeyValueModel<ApplicationTypeEnum>.GetAllCode();
        return ResultModel<List<KeyValueModel<ApplicationTypeEnum>>>.Success(result, "获取成功");
    }

    /// <summary>
    /// 获取所有返回对象类型枚举
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public ResultModel<List<KeyValueModel<ResultType>>> GetAllResultType()
    {
        List<KeyValueModel<ResultType>> result = KeyValueModel<ResultType>.GetAllCode();
        return ResultModel<List<KeyValueModel<ResultType>>>.Success(result, "获取成功");
    }
}
