/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorControllersCodeAsync>d__7.MoveNext */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalEnvironment;
using MateralReleaseCenter.DeployServer.Abstractions.RequestModel.GlobalEnvironment;
using MateralReleaseCenter.DeployServer.Abstractions.Services.Models.GlobalEnvironment;

namespace MateralReleaseCenter.DeployServer.Application.Controllers;

/// <summary>
/// 全局环境变量控制器
/// </summary>

public partial class GlobalEnvironmentController : DeployServerController<AddGlobalEnvironmentRequestModel, EditGlobalEnvironmentRequestModel, QueryGlobalEnvironmentRequestModel, AddGlobalEnvironmentModel, EditGlobalEnvironmentModel, QueryGlobalEnvironmentModel, GlobalEnvironmentDTO, GlobalEnvironmentListDTO, IGlobalEnvironmentService>, IGlobalEnvironmentController
{
}
