/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorControllersCodeAsync>d__7.MoveNext */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalParameter;
using MateralReleaseCenter.DeployServer.Abstractions.RequestModel.GlobalParameter;
using MateralReleaseCenter.DeployServer.Abstractions.Services.Models.GlobalParameter;

namespace MateralReleaseCenter.DeployServer.Application.Controllers;

/// <summary>
/// 全局参数控制器
/// </summary>

public partial class GlobalParameterController : DeployServerController<AddGlobalParameterRequestModel, EditGlobalParameterRequestModel, QueryGlobalParameterRequestModel, AddGlobalParameterModel, EditGlobalParameterModel, QueryGlobalParameterModel, GlobalParameterDTO, GlobalParameterListDTO, IGlobalParameterService>, IGlobalParameterController
{
}
