/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, serializeChangePasswordRequestModel, serializeResultModel, type ChangePasswordRequestModel, type ResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/User/ChangePassword
 */
export interface ChangePasswordRequestBuilder extends BaseRequestBuilder<ChangePasswordRequestBuilder> {
    /**
     * 修改密码
     * @param body 更改密码请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     post(body: ChangePasswordRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ResultModel | undefined>;
    /**
     * 修改密码
     * @param body 更改密码请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ChangePasswordRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ChangePasswordRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/User/ChangePassword";
/**
 * Metadata for all the requests in the request builder.
 */
export const ChangePasswordRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ChangePasswordRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeChangePasswordRequestModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
