/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorIServicesCodeAsync */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.ApplicationInfo;
using MateralReleaseCenter.DeployServer.Abstractions.Services.Models.ApplicationInfo;

namespace MateralReleaseCenter.DeployServer.Abstractions.Services
{
    /// <summary>
    /// 应用程序信息服务
    /// </summary>
    public partial interface IApplicationInfoService : IBaseService<AddApplicationInfoModel, EditApplicationInfoModel, QueryApplicationInfoModel, ApplicationInfoDTO, ApplicationInfoListDTO>
    {
    }
}
