/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorIServicesCodeAsync */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalEnvironment;
using MateralReleaseCenter.DeployServer.Abstractions.Services.Models.GlobalEnvironment;

namespace MateralReleaseCenter.DeployServer.Abstractions.Services
{
    /// <summary>
    /// 全局环境变量服务
    /// </summary>
    public partial interface IGlobalEnvironmentService : IBaseService<AddGlobalEnvironmentModel, EditGlobalEnvironmentModel, QueryGlobalEnvironmentModel, GlobalEnvironmentDTO, GlobalEnvironmentListDTO>
    {
    }
}
