/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorIServicesCodeAsync */

using MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalParameter;
using MateralReleaseCenter.DeployServer.Abstractions.Services.Models.GlobalParameter;

namespace MateralReleaseCenter.DeployServer.Abstractions.Services
{
    /// <summary>
    /// 全局参数服务
    /// </summary>
    public partial interface IGlobalParameterService : IBaseService<AddGlobalParameterModel, EditGlobalParameterModel, QueryGlobalParameterModel, GlobalParameterDTO, GlobalParameterListDTO>
    {
    }
}
