/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.DTOGeneratorCodePlug+<GeneratorDTOModelAsync>d__8.MoveNext */

namespace MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalParameter;

/// <summary>
/// 全局参数数据传输模型
/// </summary>
public partial class GlobalParameterDTO : GlobalParameterListDTO, IDTO
{
}
