/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.DTOGeneratorCodePlug+<GeneratorListDTOModelAsync>d__7.MoveNext */

namespace MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalParameter;

/// <summary>
/// 全局参数列表数据传输模型
/// </summary>
public partial class GlobalParameterListDTO : IListDTO
{
    /// <summary>
    /// 唯一标识
    /// </summary>
    [Required(ErrorMessage = "唯一标识为空")]
    public Guid ID { get; set; }
    /// <summary>
    /// 创建时间
    /// </summary>
    [Required(ErrorMessage = "创建时间为空")]
    public DateTime CreateTime { get; set; }
    /// <summary>
    /// 应用程序类型
    /// </summary>
    [Required(ErrorMessage = "应用程序类型为空")]
    public ApplicationTypeEnum ApplicationType { get; set; }
    /// <summary>
    /// 名称
    /// </summary>
    [Required(ErrorMessage = "名称为空")]
    public string Name { get; set; } = string.Empty;
    /// <summary>
    /// 值
    /// </summary>
    [Required(ErrorMessage = "值为空")]
    public string Value { get; set; } = string.Empty;
}
