/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, type ResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/Kill
 */
export interface KillRequestBuilder extends BaseRequestBuilder<KillRequestBuilder> {
    /**
     * 杀死程序
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     post(requestConfiguration?: RequestConfiguration<KillRequestBuilderPostQueryParameters> | undefined) : Promise<ResultModel | undefined>;
    /**
     * 杀死程序
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<KillRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * 杀死程序
 */
export interface KillRequestBuilderPostQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const KillRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/Kill{?id*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const KillRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: KillRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
