/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * 配置项添加请求模型
 */
export interface AddConfigurationItemRequestModel extends Parsable {
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 键
     */
    key?: string | null;
    /**
     * 命名空间唯一标识
     */
    namespaceID?: Guid | null;
    /**
     * 值
     */
    value?: string | null;
}
/**
 * 配置项数据传输模型
 */
export interface ConfigurationItemDTO extends Parsable {
    /**
     * 创建时间
     */
    createTime?: Date | null;
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 键
     */
    key?: string | null;
    /**
     * 命名空间唯一标识
     */
    namespaceID?: Guid | null;
    /**
     * 命名空间名称
     */
    namespaceName?: string | null;
    /**
     * 项目唯一标识
     */
    projectID?: Guid | null;
    /**
     * 项目名称
     */
    projectName?: string | null;
    /**
     * 值
     */
    value?: string | null;
}
export interface ConfigurationItemDTOResultModel extends Parsable {
    /**
     * 配置项数据传输模型
     */
    data?: ConfigurationItemDTO | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * 配置项列表数据传输模型
 */
export interface ConfigurationItemListDTO extends Parsable {
    /**
     * 创建时间
     */
    createTime?: Date | null;
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 键
     */
    key?: string | null;
    /**
     * 命名空间唯一标识
     */
    namespaceID?: Guid | null;
    /**
     * 命名空间名称
     */
    namespaceName?: string | null;
    /**
     * 项目唯一标识
     */
    projectID?: Guid | null;
    /**
     * 项目名称
     */
    projectName?: string | null;
    /**
     * 值
     */
    value?: string | null;
}
export interface ConfigurationItemListDTOCollectionResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: ConfigurationItemListDTO[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The PageModel property
     */
    pageModel?: PageModel | null;
    /**
     * The RangeModel property
     */
    rangeModel?: RangeModel | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AddConfigurationItemRequestModel}
 */
// @ts-ignore
export function createAddConfigurationItemRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAddConfigurationItemRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ConfigurationItemDTO}
 */
// @ts-ignore
export function createConfigurationItemDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoConfigurationItemDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ConfigurationItemDTOResultModel}
 */
// @ts-ignore
export function createConfigurationItemDTOResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoConfigurationItemDTOResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ConfigurationItemListDTOCollectionResultModel}
 */
// @ts-ignore
export function createConfigurationItemListDTOCollectionResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoConfigurationItemListDTOCollectionResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ConfigurationItemListDTO}
 */
// @ts-ignore
export function createConfigurationItemListDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoConfigurationItemListDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EditConfigurationItemRequestModel}
 */
// @ts-ignore
export function createEditConfigurationItemRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEditConfigurationItemRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GuidResultModel}
 */
// @ts-ignore
export function createGuidResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGuidResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PageModel}
 */
// @ts-ignore
export function createPageModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPageModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryConfigurationItemRequestModel}
 */
// @ts-ignore
export function createQueryConfigurationItemRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryConfigurationItemRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RangeModel}
 */
// @ts-ignore
export function createRangeModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRangeModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResultModel}
 */
// @ts-ignore
export function createResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResultTypeKeyValueModel}
 */
// @ts-ignore
export function createResultTypeKeyValueModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResultTypeKeyValueModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResultTypeKeyValueModelListResultModel}
 */
// @ts-ignore
export function createResultTypeKeyValueModelListResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResultTypeKeyValueModelListResultModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SyncConfigRequestModel}
 */
// @ts-ignore
export function createSyncConfigRequestModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSyncConfigRequestModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SyncModeEnumKeyValueModel}
 */
// @ts-ignore
export function createSyncModeEnumKeyValueModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSyncModeEnumKeyValueModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SyncModeEnumKeyValueModelListResultModel}
 */
// @ts-ignore
export function createSyncModeEnumKeyValueModelListResultModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSyncModeEnumKeyValueModelListResultModel;
}
/**
 * The deserialization information for the current model
 * @param AddConfigurationItemRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAddConfigurationItemRequestModel(addConfigurationItemRequestModel: Partial<AddConfigurationItemRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Description": n => { addConfigurationItemRequestModel.description = n.getStringValue(); },
        "Key": n => { addConfigurationItemRequestModel.key = n.getStringValue(); },
        "NamespaceID": n => { addConfigurationItemRequestModel.namespaceID = n.getGuidValue(); },
        "Value": n => { addConfigurationItemRequestModel.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ConfigurationItemDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoConfigurationItemDTO(configurationItemDTO: Partial<ConfigurationItemDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "CreateTime": n => { configurationItemDTO.createTime = n.getDateValue(); },
        "Description": n => { configurationItemDTO.description = n.getStringValue(); },
        "ID": n => { configurationItemDTO.iD = n.getGuidValue(); },
        "Key": n => { configurationItemDTO.key = n.getStringValue(); },
        "NamespaceID": n => { configurationItemDTO.namespaceID = n.getGuidValue(); },
        "NamespaceName": n => { configurationItemDTO.namespaceName = n.getStringValue(); },
        "ProjectID": n => { configurationItemDTO.projectID = n.getGuidValue(); },
        "ProjectName": n => { configurationItemDTO.projectName = n.getStringValue(); },
        "Value": n => { configurationItemDTO.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ConfigurationItemDTOResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoConfigurationItemDTOResultModel(configurationItemDTOResultModel: Partial<ConfigurationItemDTOResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { configurationItemDTOResultModel.data = n.getObjectValue<ConfigurationItemDTO>(createConfigurationItemDTOFromDiscriminatorValue); },
        "Message": n => { configurationItemDTOResultModel.message = n.getStringValue(); },
        "ResultType": n => { configurationItemDTOResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ConfigurationItemListDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoConfigurationItemListDTO(configurationItemListDTO: Partial<ConfigurationItemListDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "CreateTime": n => { configurationItemListDTO.createTime = n.getDateValue(); },
        "Description": n => { configurationItemListDTO.description = n.getStringValue(); },
        "ID": n => { configurationItemListDTO.iD = n.getGuidValue(); },
        "Key": n => { configurationItemListDTO.key = n.getStringValue(); },
        "NamespaceID": n => { configurationItemListDTO.namespaceID = n.getGuidValue(); },
        "NamespaceName": n => { configurationItemListDTO.namespaceName = n.getStringValue(); },
        "ProjectID": n => { configurationItemListDTO.projectID = n.getGuidValue(); },
        "ProjectName": n => { configurationItemListDTO.projectName = n.getStringValue(); },
        "Value": n => { configurationItemListDTO.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ConfigurationItemListDTOCollectionResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoConfigurationItemListDTOCollectionResultModel(configurationItemListDTOCollectionResultModel: Partial<ConfigurationItemListDTOCollectionResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { configurationItemListDTOCollectionResultModel.data = n.getCollectionOfObjectValues<ConfigurationItemListDTO>(createConfigurationItemListDTOFromDiscriminatorValue); },
        "Message": n => { configurationItemListDTOCollectionResultModel.message = n.getStringValue(); },
        "PageModel": n => { configurationItemListDTOCollectionResultModel.pageModel = n.getObjectValue<PageModel>(createPageModelFromDiscriminatorValue); },
        "RangeModel": n => { configurationItemListDTOCollectionResultModel.rangeModel = n.getObjectValue<RangeModel>(createRangeModelFromDiscriminatorValue); },
        "ResultType": n => { configurationItemListDTOCollectionResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EditConfigurationItemRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEditConfigurationItemRequestModel(editConfigurationItemRequestModel: Partial<EditConfigurationItemRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Description": n => { editConfigurationItemRequestModel.description = n.getStringValue(); },
        "ID": n => { editConfigurationItemRequestModel.iD = n.getGuidValue(); },
        "Key": n => { editConfigurationItemRequestModel.key = n.getStringValue(); },
        "Value": n => { editConfigurationItemRequestModel.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param GuidResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGuidResultModel(guidResultModel: Partial<GuidResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { guidResultModel.data = n.getGuidValue(); },
        "Message": n => { guidResultModel.message = n.getStringValue(); },
        "ResultType": n => { guidResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PageModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPageModel(pageModel: Partial<PageModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "DataCount": n => { pageModel.dataCount = n.getNumberValue(); },
        "IsAsc": n => { pageModel.isAsc = n.getBooleanValue(); },
        "PageCount": n => { pageModel.pageCount = n.getNumberValue(); },
        "PageIndex": n => { pageModel.pageIndex = n.getNumberValue(); },
        "PageSize": n => { pageModel.pageSize = n.getNumberValue(); },
        "Skip": n => { pageModel.skip = n.getNumberValue(); },
        "SortPropertyName": n => { pageModel.sortPropertyName = n.getStringValue(); },
        "StartIndex": n => { pageModel.startIndex = n.getNumberValue(); },
        "Take": n => { pageModel.take = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QueryConfigurationItemRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryConfigurationItemRequestModel(queryConfigurationItemRequestModel: Partial<QueryConfigurationItemRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "IDs": n => { queryConfigurationItemRequestModel.iDs = n.getCollectionOfPrimitiveValues<Guid>(); },
        "IsAsc": n => { queryConfigurationItemRequestModel.isAsc = n.getBooleanValue(); },
        "Key": n => { queryConfigurationItemRequestModel.key = n.getStringValue(); },
        "MaxCreateTime": n => { queryConfigurationItemRequestModel.maxCreateTime = n.getDateValue(); },
        "MinCreateTime": n => { queryConfigurationItemRequestModel.minCreateTime = n.getDateValue(); },
        "NamespaceID": n => { queryConfigurationItemRequestModel.namespaceID = n.getGuidValue(); },
        "NamespaceIDs": n => { queryConfigurationItemRequestModel.namespaceIDs = n.getCollectionOfPrimitiveValues<Guid>(); },
        "NamespaceName": n => { queryConfigurationItemRequestModel.namespaceName = n.getStringValue(); },
        "NamespaceNames": n => { queryConfigurationItemRequestModel.namespaceNames = n.getCollectionOfPrimitiveValues<string>(); },
        "PageIndex": n => { queryConfigurationItemRequestModel.pageIndex = n.getNumberValue(); },
        "PageSize": n => { queryConfigurationItemRequestModel.pageSize = n.getNumberValue(); },
        "ProjectID": n => { queryConfigurationItemRequestModel.projectID = n.getGuidValue(); },
        "ProjectName": n => { queryConfigurationItemRequestModel.projectName = n.getStringValue(); },
        "Skip": n => { queryConfigurationItemRequestModel.skip = n.getNumberValue(); },
        "SortPropertyName": n => { queryConfigurationItemRequestModel.sortPropertyName = n.getStringValue(); },
        "Take": n => { queryConfigurationItemRequestModel.take = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RangeModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRangeModel(rangeModel: Partial<RangeModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "DataCount": n => { rangeModel.dataCount = n.getNumberValue(); },
        "IsAsc": n => { rangeModel.isAsc = n.getBooleanValue(); },
        "Skip": n => { rangeModel.skip = n.getNumberValue(); },
        "SortPropertyName": n => { rangeModel.sortPropertyName = n.getStringValue(); },
        "Take": n => { rangeModel.take = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResultModel(resultModel: Partial<ResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Message": n => { resultModel.message = n.getStringValue(); },
        "ResultType": n => { resultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ResultTypeKeyValueModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResultTypeKeyValueModel(resultTypeKeyValueModel: Partial<ResultTypeKeyValueModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Key": n => { resultTypeKeyValueModel.key = n.getNumberValue(); },
        "Value": n => { resultTypeKeyValueModel.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ResultTypeKeyValueModelListResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResultTypeKeyValueModelListResultModel(resultTypeKeyValueModelListResultModel: Partial<ResultTypeKeyValueModelListResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { resultTypeKeyValueModelListResultModel.data = n.getCollectionOfObjectValues<ResultTypeKeyValueModel>(createResultTypeKeyValueModelFromDiscriminatorValue); },
        "Message": n => { resultTypeKeyValueModelListResultModel.message = n.getStringValue(); },
        "ResultType": n => { resultTypeKeyValueModelListResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SyncConfigRequestModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSyncConfigRequestModel(syncConfigRequestModel: Partial<SyncConfigRequestModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Mode": n => { syncConfigRequestModel.mode = n.getNumberValue(); },
        "NamespaceIDs": n => { syncConfigRequestModel.namespaceIDs = n.getCollectionOfPrimitiveValues<Guid>(); },
        "ProjectID": n => { syncConfigRequestModel.projectID = n.getGuidValue(); },
        "TargetEnvironments": n => { syncConfigRequestModel.targetEnvironments = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SyncModeEnumKeyValueModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSyncModeEnumKeyValueModel(syncModeEnumKeyValueModel: Partial<SyncModeEnumKeyValueModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Key": n => { syncModeEnumKeyValueModel.key = n.getNumberValue(); },
        "Value": n => { syncModeEnumKeyValueModel.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SyncModeEnumKeyValueModelListResultModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSyncModeEnumKeyValueModelListResultModel(syncModeEnumKeyValueModelListResultModel: Partial<SyncModeEnumKeyValueModelListResultModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Data": n => { syncModeEnumKeyValueModelListResultModel.data = n.getCollectionOfObjectValues<SyncModeEnumKeyValueModel>(createSyncModeEnumKeyValueModelFromDiscriminatorValue); },
        "Message": n => { syncModeEnumKeyValueModelListResultModel.message = n.getStringValue(); },
        "ResultType": n => { syncModeEnumKeyValueModelListResultModel.resultType = n.getNumberValue(); },
    }
}
/**
 * 配置项修改请求模型
 */
export interface EditConfigurationItemRequestModel extends Parsable {
    /**
     * 描述
     */
    description?: string | null;
    /**
     * 唯一标识
     */
    iD?: Guid | null;
    /**
     * 键
     */
    key?: string | null;
    /**
     * 值
     */
    value?: string | null;
}
export interface GuidResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: Guid | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
export interface PageModel extends Parsable {
    /**
     * The DataCount property
     */
    dataCount?: number | null;
    /**
     * The IsAsc property
     */
    isAsc?: boolean | null;
    /**
     * The PageCount property
     */
    pageCount?: number | null;
    /**
     * The PageIndex property
     */
    pageIndex?: number | null;
    /**
     * The PageSize property
     */
    pageSize?: number | null;
    /**
     * The Skip property
     */
    skip?: number | null;
    /**
     * The SortPropertyName property
     */
    sortPropertyName?: string | null;
    /**
     * The StartIndex property
     */
    startIndex?: number | null;
    /**
     * The Take property
     */
    take?: number | null;
}
/**
 * 配置项查询请求模型
 */
export interface QueryConfigurationItemRequestModel extends Parsable {
    /**
     * 唯一标识组
     */
    iDs?: Guid[] | null;
    /**
     * The IsAsc property
     */
    isAsc?: boolean | null;
    /**
     * 键
     */
    key?: string | null;
    /**
     * 最大创建时间
     */
    maxCreateTime?: Date | null;
    /**
     * 最小创建时间
     */
    minCreateTime?: Date | null;
    /**
     * 命名空间唯一标识
     */
    namespaceID?: Guid | null;
    /**
     * 命名空间唯一标识
     */
    namespaceIDs?: Guid[] | null;
    /**
     * 命名空间名称
     */
    namespaceName?: string | null;
    /**
     * 命名空间名称组
     */
    namespaceNames?: string[] | null;
    /**
     * The PageIndex property
     */
    pageIndex?: number | null;
    /**
     * The PageSize property
     */
    pageSize?: number | null;
    /**
     * 项目唯一标识
     */
    projectID?: Guid | null;
    /**
     * 项目名称
     */
    projectName?: string | null;
    /**
     * The Skip property
     */
    skip?: number | null;
    /**
     * The SortPropertyName property
     */
    sortPropertyName?: string | null;
    /**
     * The Take property
     */
    take?: number | null;
}
export interface RangeModel extends Parsable {
    /**
     * The DataCount property
     */
    dataCount?: number | null;
    /**
     * The IsAsc property
     */
    isAsc?: boolean | null;
    /**
     * The Skip property
     */
    skip?: number | null;
    /**
     * The SortPropertyName property
     */
    sortPropertyName?: string | null;
    /**
     * The Take property
     */
    take?: number | null;
}
export interface ResultModel extends Parsable {
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
export interface ResultTypeKeyValueModel extends Parsable {
    /**
     * The Key property
     */
    key?: number | null;
    /**
     * The Value property
     */
    value?: string | null;
}
export interface ResultTypeKeyValueModelListResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: ResultTypeKeyValueModel[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/**
 * Serializes information the current object
 * @param AddConfigurationItemRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAddConfigurationItemRequestModel(writer: SerializationWriter, addConfigurationItemRequestModel: Partial<AddConfigurationItemRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!addConfigurationItemRequestModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Description", addConfigurationItemRequestModel.description);
    writer.writeStringValue("Key", addConfigurationItemRequestModel.key);
    writer.writeGuidValue("NamespaceID", addConfigurationItemRequestModel.namespaceID);
    writer.writeStringValue("Value", addConfigurationItemRequestModel.value);
}
/**
 * Serializes information the current object
 * @param ConfigurationItemDTO The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeConfigurationItemDTO(writer: SerializationWriter, configurationItemDTO: Partial<ConfigurationItemDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!configurationItemDTO || isSerializingDerivedType) { return; }
    writer.writeDateValue("CreateTime", configurationItemDTO.createTime);
    writer.writeStringValue("Description", configurationItemDTO.description);
    writer.writeGuidValue("ID", configurationItemDTO.iD);
    writer.writeStringValue("Key", configurationItemDTO.key);
    writer.writeGuidValue("NamespaceID", configurationItemDTO.namespaceID);
    writer.writeStringValue("NamespaceName", configurationItemDTO.namespaceName);
    writer.writeGuidValue("ProjectID", configurationItemDTO.projectID);
    writer.writeStringValue("ProjectName", configurationItemDTO.projectName);
    writer.writeStringValue("Value", configurationItemDTO.value);
}
/**
 * Serializes information the current object
 * @param ConfigurationItemDTOResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeConfigurationItemDTOResultModel(writer: SerializationWriter, configurationItemDTOResultModel: Partial<ConfigurationItemDTOResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!configurationItemDTOResultModel || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ConfigurationItemDTO>("Data", configurationItemDTOResultModel.data, serializeConfigurationItemDTO);
    writer.writeStringValue("Message", configurationItemDTOResultModel.message);
    writer.writeNumberValue("ResultType", configurationItemDTOResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param ConfigurationItemListDTO The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeConfigurationItemListDTO(writer: SerializationWriter, configurationItemListDTO: Partial<ConfigurationItemListDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!configurationItemListDTO || isSerializingDerivedType) { return; }
    writer.writeDateValue("CreateTime", configurationItemListDTO.createTime);
    writer.writeStringValue("Description", configurationItemListDTO.description);
    writer.writeGuidValue("ID", configurationItemListDTO.iD);
    writer.writeStringValue("Key", configurationItemListDTO.key);
    writer.writeGuidValue("NamespaceID", configurationItemListDTO.namespaceID);
    writer.writeStringValue("NamespaceName", configurationItemListDTO.namespaceName);
    writer.writeGuidValue("ProjectID", configurationItemListDTO.projectID);
    writer.writeStringValue("ProjectName", configurationItemListDTO.projectName);
    writer.writeStringValue("Value", configurationItemListDTO.value);
}
/**
 * Serializes information the current object
 * @param ConfigurationItemListDTOCollectionResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeConfigurationItemListDTOCollectionResultModel(writer: SerializationWriter, configurationItemListDTOCollectionResultModel: Partial<ConfigurationItemListDTOCollectionResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!configurationItemListDTOCollectionResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ConfigurationItemListDTO>("Data", configurationItemListDTOCollectionResultModel.data, serializeConfigurationItemListDTO);
    writer.writeStringValue("Message", configurationItemListDTOCollectionResultModel.message);
    writer.writeObjectValue<PageModel>("PageModel", configurationItemListDTOCollectionResultModel.pageModel, serializePageModel);
    writer.writeObjectValue<RangeModel>("RangeModel", configurationItemListDTOCollectionResultModel.rangeModel, serializeRangeModel);
    writer.writeNumberValue("ResultType", configurationItemListDTOCollectionResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param EditConfigurationItemRequestModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEditConfigurationItemRequestModel(writer: SerializationWriter, editConfigurationItemRequestModel: Partial<EditConfigurationItemRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!editConfigurationItemRequestModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Description", editConfigurationItemRequestModel.description);
    writer.writeGuidValue("ID", editConfigurationItemRequestModel.iD);
    writer.writeStringValue("Key", editConfigurationItemRequestModel.key);
    writer.writeStringValue("Value", editConfigurationItemRequestModel.value);
}
/**
 * Serializes information the current object
 * @param GuidResultModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGuidResultModel(writer: SerializationWriter, guidResultModel: Partial<GuidResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!guidResultModel || isSerializingDerivedType) { return; }
    writer.writeGuidValue("Data", guidResultModel.data);
    writer.writeStringValue("Message", guidResultModel.message);
    writer.writeNumberValue("ResultType", guidResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PageModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePageModel(writer: SerializationWriter, pageModel: Partial<PageModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pageModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("DataCount", pageModel.dataCount);
    writer.writeBooleanValue("IsAsc", pageModel.isAsc);
    writer.writeNumberValue("PageIndex", pageModel.pageIndex);
    writer.writeNumberValue("PageSize", pageModel.pageSize);
    writer.writeNumberValue("Skip", pageModel.skip);
    writer.writeStringValue("SortPropertyName", pageModel.sortPropertyName);
    writer.writeNumberValue("Take", pageModel.take);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QueryConfigurationItemRequestModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryConfigurationItemRequestModel(writer: SerializationWriter, queryConfigurationItemRequestModel: Partial<QueryConfigurationItemRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!queryConfigurationItemRequestModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<Guid>("IDs", queryConfigurationItemRequestModel.iDs);
    writer.writeBooleanValue("IsAsc", queryConfigurationItemRequestModel.isAsc);
    writer.writeStringValue("Key", queryConfigurationItemRequestModel.key);
    writer.writeDateValue("MaxCreateTime", queryConfigurationItemRequestModel.maxCreateTime);
    writer.writeDateValue("MinCreateTime", queryConfigurationItemRequestModel.minCreateTime);
    writer.writeGuidValue("NamespaceID", queryConfigurationItemRequestModel.namespaceID);
    writer.writeCollectionOfPrimitiveValues<Guid>("NamespaceIDs", queryConfigurationItemRequestModel.namespaceIDs);
    writer.writeStringValue("NamespaceName", queryConfigurationItemRequestModel.namespaceName);
    writer.writeCollectionOfPrimitiveValues<string>("NamespaceNames", queryConfigurationItemRequestModel.namespaceNames);
    writer.writeNumberValue("PageIndex", queryConfigurationItemRequestModel.pageIndex);
    writer.writeNumberValue("PageSize", queryConfigurationItemRequestModel.pageSize);
    writer.writeGuidValue("ProjectID", queryConfigurationItemRequestModel.projectID);
    writer.writeStringValue("ProjectName", queryConfigurationItemRequestModel.projectName);
    writer.writeNumberValue("Skip", queryConfigurationItemRequestModel.skip);
    writer.writeStringValue("SortPropertyName", queryConfigurationItemRequestModel.sortPropertyName);
    writer.writeNumberValue("Take", queryConfigurationItemRequestModel.take);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RangeModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRangeModel(writer: SerializationWriter, rangeModel: Partial<RangeModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!rangeModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("DataCount", rangeModel.dataCount);
    writer.writeBooleanValue("IsAsc", rangeModel.isAsc);
    writer.writeNumberValue("Skip", rangeModel.skip);
    writer.writeStringValue("SortPropertyName", rangeModel.sortPropertyName);
    writer.writeNumberValue("Take", rangeModel.take);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResultModel(writer: SerializationWriter, resultModel: Partial<ResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!resultModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("Message", resultModel.message);
    writer.writeNumberValue("ResultType", resultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResultTypeKeyValueModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResultTypeKeyValueModel(writer: SerializationWriter, resultTypeKeyValueModel: Partial<ResultTypeKeyValueModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!resultTypeKeyValueModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("Key", resultTypeKeyValueModel.key);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResultTypeKeyValueModelListResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResultTypeKeyValueModelListResultModel(writer: SerializationWriter, resultTypeKeyValueModelListResultModel: Partial<ResultTypeKeyValueModelListResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!resultTypeKeyValueModelListResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ResultTypeKeyValueModel>("Data", resultTypeKeyValueModelListResultModel.data, serializeResultTypeKeyValueModel);
    writer.writeStringValue("Message", resultTypeKeyValueModelListResultModel.message);
    writer.writeNumberValue("ResultType", resultTypeKeyValueModelListResultModel.resultType);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SyncConfigRequestModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSyncConfigRequestModel(writer: SerializationWriter, syncConfigRequestModel: Partial<SyncConfigRequestModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!syncConfigRequestModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("Mode", syncConfigRequestModel.mode);
    writer.writeCollectionOfPrimitiveValues<Guid>("NamespaceIDs", syncConfigRequestModel.namespaceIDs);
    writer.writeGuidValue("ProjectID", syncConfigRequestModel.projectID);
    writer.writeCollectionOfPrimitiveValues<string>("TargetEnvironments", syncConfigRequestModel.targetEnvironments);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SyncModeEnumKeyValueModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSyncModeEnumKeyValueModel(writer: SerializationWriter, syncModeEnumKeyValueModel: Partial<SyncModeEnumKeyValueModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!syncModeEnumKeyValueModel || isSerializingDerivedType) { return; }
    writer.writeNumberValue("Key", syncModeEnumKeyValueModel.key);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SyncModeEnumKeyValueModelListResultModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSyncModeEnumKeyValueModelListResultModel(writer: SerializationWriter, syncModeEnumKeyValueModelListResultModel: Partial<SyncModeEnumKeyValueModelListResultModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!syncModeEnumKeyValueModelListResultModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<SyncModeEnumKeyValueModel>("Data", syncModeEnumKeyValueModelListResultModel.data, serializeSyncModeEnumKeyValueModel);
    writer.writeStringValue("Message", syncModeEnumKeyValueModelListResultModel.message);
    writer.writeNumberValue("ResultType", syncModeEnumKeyValueModelListResultModel.resultType);
}
/**
 * 同步配置请求模型
 */
export interface SyncConfigRequestModel extends Parsable {
    /**
     * 同步模式枚举
     */
    mode?: number | null;
    /**
     * 命名空间唯一标识
     */
    namespaceIDs?: Guid[] | null;
    /**
     * 项目唯一标识
     */
    projectID?: Guid | null;
    /**
     * 目标源环境
     */
    targetEnvironments?: string[] | null;
}
export interface SyncModeEnumKeyValueModel extends Parsable {
    /**
     * 同步模式枚举
     */
    key?: number | null;
    /**
     * The Value property
     */
    value?: string | null;
}
export interface SyncModeEnumKeyValueModelListResultModel extends Parsable {
    /**
     * The Data property
     */
    data?: SyncModeEnumKeyValueModel[] | null;
    /**
     * The Message property
     */
    message?: string | null;
    /**
     * The ResultType property
     */
    resultType?: number | null;
}
/* tslint:enable */
/* eslint-enable */
