/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, type ResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/Server/SourceCodeUpdate
 */
export interface SourceCodeUpdateRequestBuilder extends BaseRequestBuilder<SourceCodeUpdateRequestBuilder> {
    /**
     * 源码更新
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     get(requestConfiguration?: RequestConfiguration<SourceCodeUpdateRequestBuilderGetQueryParameters> | undefined) : Promise<ResultModel | undefined>;
    /**
     * 源码更新
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SourceCodeUpdateRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * 源码更新
 */
export interface SourceCodeUpdateRequestBuilderGetQueryParameters {
    url?: string;
}
/**
 * Uri template for the request builder.
 */
export const SourceCodeUpdateRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/Server/SourceCodeUpdate{?url*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const SourceCodeUpdateRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SourceCodeUpdateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
