/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { GetAllApplicationStatusEnumRequestBuilderRequestsMetadata, type GetAllApplicationStatusEnumRequestBuilder } from './getAllApplicationStatusEnum/index.js';
// @ts-ignore
import { GetAllApplicationTypeEnumRequestBuilderRequestsMetadata, type GetAllApplicationTypeEnumRequestBuilder } from './getAllApplicationTypeEnum/index.js';
// @ts-ignore
import { GetAllResultTypeRequestBuilderRequestsMetadata, type GetAllResultTypeRequestBuilder } from './getAllResultType/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/Enums
 */
export interface EnumsRequestBuilder extends BaseRequestBuilder<EnumsRequestBuilder> {
    /**
     * The GetAllApplicationStatusEnum property
     */
    get getAllApplicationStatusEnum(): GetAllApplicationStatusEnumRequestBuilder;
    /**
     * The GetAllApplicationTypeEnum property
     */
    get getAllApplicationTypeEnum(): GetAllApplicationTypeEnumRequestBuilder;
    /**
     * The GetAllResultType property
     */
    get getAllResultType(): GetAllResultTypeRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const EnumsRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/Enums";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EnumsRequestBuilderNavigationMetadata: Record<Exclude<keyof EnumsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    getAllApplicationStatusEnum: {
        requestsMetadata: GetAllApplicationStatusEnumRequestBuilderRequestsMetadata,
    },
    getAllApplicationTypeEnum: {
        requestsMetadata: GetAllApplicationTypeEnumRequestBuilderRequestsMetadata,
    },
    getAllResultType: {
        requestsMetadata: GetAllResultTypeRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
