/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGlobalEnvironmentListDTOCollectionResultModelFromDiscriminatorValue, serializeGlobalEnvironmentListDTOCollectionResultModel, serializeQueryGlobalEnvironmentRequestModel, type GlobalEnvironmentListDTOCollectionResultModel, type QueryGlobalEnvironmentRequestModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/GlobalEnvironment/GetList
 */
export interface GetListRequestBuilder extends BaseRequestBuilder<GetListRequestBuilder> {
    /**
     * @param body 全局环境变量查询请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GlobalEnvironmentListDTOCollectionResultModel>}
     */
     post(body: QueryGlobalEnvironmentRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GlobalEnvironmentListDTOCollectionResultModel | undefined>;
    /**
     * @param body 全局环境变量查询请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryGlobalEnvironmentRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetListRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/GlobalEnvironment/GetList";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: GetListRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createGlobalEnvironmentListDTOCollectionResultModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryGlobalEnvironmentRequestModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
