/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProjectListDTOCollectionResultModelFromDiscriminatorValue, serializeProjectListDTOCollectionResultModel, serializeQueryProjectRequestModel, type ProjectListDTOCollectionResultModel, type QueryProjectRequestModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/Project/GetList
 */
export interface GetListRequestBuilder extends BaseRequestBuilder<GetListRequestBuilder> {
    /**
     * @param body 项目查询请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ProjectListDTOCollectionResultModel>}
     */
     post(body: QueryProjectRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ProjectListDTOCollectionResultModel | undefined>;
    /**
     * @param body 项目查询请求模型
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryProjectRequestModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetListRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/Project/GetList";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: GetListRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createProjectListDTOCollectionResultModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryProjectRequestModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
