/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createStringICollectionResultModelFromDiscriminatorValue, type StringICollectionResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/GetConsoleMessages
 */
export interface GetConsoleMessagesRequestBuilder extends BaseRequestBuilder<GetConsoleMessagesRequestBuilder> {
    /**
     * 获得控制台信息
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<StringICollectionResultModel>}
     */
     get(requestConfiguration?: RequestConfiguration<GetConsoleMessagesRequestBuilderGetQueryParameters> | undefined) : Promise<StringICollectionResultModel | undefined>;
    /**
     * 获得控制台信息
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<GetConsoleMessagesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * 获得控制台信息
 */
export interface GetConsoleMessagesRequestBuilderGetQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const GetConsoleMessagesRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/GetConsoleMessages{?id*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetConsoleMessagesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetConsoleMessagesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createStringICollectionResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
