/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDefaultDataDTOResultModelFromDiscriminatorValue, type DefaultDataDTOResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/DefaultData/GetInfo
 */
export interface GetInfoRequestBuilder extends BaseRequestBuilder<GetInfoRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DefaultDataDTOResultModel>}
     */
     get(requestConfiguration?: RequestConfiguration<GetInfoRequestBuilderGetQueryParameters> | undefined) : Promise<DefaultDataDTOResultModel | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<GetInfoRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface GetInfoRequestBuilderGetQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const GetInfoRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/DefaultData/GetInfo?id={id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetInfoRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetInfoRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createDefaultDataDTOResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
