/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.DTOGeneratorCodePlug+<GeneratorDTOModelAsync>d__8.MoveNext */

namespace MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalEnvironment;

/// <summary>
/// 全局环境变量数据传输模型
/// </summary>
public partial class GlobalEnvironmentDTO : GlobalEnvironmentListDTO, IDTO
{
}
