/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.DTOGeneratorCodePlug+<GeneratorListDTOModelAsync>d__7.MoveNext */

namespace MateralReleaseCenter.DeployServer.Abstractions.DTO.GlobalEnvironment;

/// <summary>
/// 全局环境变量列表数据传输模型
/// </summary>
public partial class GlobalEnvironmentListDTO : IListDTO
{
    /// <summary>
    /// 唯一标识
    /// </summary>
    [Required(ErrorMessage = "唯一标识为空")]
    public Guid ID { get; set; }
    /// <summary>
    /// 创建时间
    /// </summary>
    [Required(ErrorMessage = "创建时间为空")]
    public DateTime CreateTime { get; set; }
    /// <summary>
    /// 应用程序类型
    /// </summary>
    [Required(ErrorMessage = "应用程序类型为空")]
    public ApplicationTypeEnum ApplicationType { get; set; }
    /// <summary>
    /// 键
    /// </summary>
    [Required(ErrorMessage = "键为空")]
    public string Key { get; set; } = string.Empty;
    /// <summary>
    /// 值
    /// </summary>
    [Required(ErrorMessage = "值为空")]
    public string Value { get; set; } = string.Empty;
    /// <summary>
    /// 描述
    /// </summary>
    public string? Description { get; set; }
}
