/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RequesetModelGeneratorCodePlug+<GeneratorAddRequestModelAsync>d__8.MoveNext */

namespace MateralReleaseCenter.DeployServer.Abstractions.RequestModel.GlobalEnvironment;
/// <summary>
/// 全局环境变量添加请求模型
/// </summary>
public partial class AddGlobalEnvironmentRequestModel : IAddRequestModel
{
    /// <summary>
    /// 应用程序类型
    /// </summary>
    [Required(ErrorMessage = "应用程序类型为空")]
    public ApplicationTypeEnum ApplicationType { get; set; }
    /// <summary>
    /// 键
    /// </summary>
    [Required(ErrorMessage = "键为空")]
    public string Key { get; set; } = string.Empty;
    /// <summary>
    /// 值
    /// </summary>
    [Required(ErrorMessage = "值为空")]
    public string Value { get; set; } = string.Empty;
    /// <summary>
    /// 描述
    /// </summary>
    public string? Description { get; set; }
}
