/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AddRequestBuilderRequestsMetadata, type AddRequestBuilder } from './add/index.js';
// @ts-ignore
import { DeleteRequestBuilderRequestsMetadata, type DeleteRequestBuilder } from './delete/index.js';
// @ts-ignore
import { EditRequestBuilderRequestsMetadata, type EditRequestBuilder } from './edit/index.js';
// @ts-ignore
import { GetInfoRequestBuilderRequestsMetadata, type GetInfoRequestBuilder } from './getInfo/index.js';
// @ts-ignore
import { GetListRequestBuilderRequestsMetadata, type GetListRequestBuilder } from './getList/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/Project
 */
export interface ProjectRequestBuilder extends BaseRequestBuilder<ProjectRequestBuilder> {
    /**
     * The Add property
     */
    get add(): AddRequestBuilder;
    /**
     * The DeletePath property
     */
    get deletePath(): DeleteRequestBuilder;
    /**
     * The Edit property
     */
    get edit(): EditRequestBuilder;
    /**
     * The GetInfo property
     */
    get getInfo(): GetInfoRequestBuilder;
    /**
     * The GetList property
     */
    get getList(): GetListRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ProjectRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/Project";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProjectRequestBuilderNavigationMetadata: Record<Exclude<keyof ProjectRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    add: {
        requestsMetadata: AddRequestBuilderRequestsMetadata,
    },
    deletePath: {
        requestsMetadata: DeleteRequestBuilderRequestsMetadata,
    },
    edit: {
        requestsMetadata: EditRequestBuilderRequestsMetadata,
    },
    getInfo: {
        requestsMetadata: GetInfoRequestBuilderRequestsMetadata,
    },
    getList: {
        requestsMetadata: GetListRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
