/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSyncModeEnumKeyValueModelListResultModelFromDiscriminatorValue, type SyncModeEnumKeyValueModelListResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /EnvironmentServerAPI/Enums/GetAllSyncModeEnum
 */
export interface GetAllSyncModeEnumRequestBuilder extends BaseRequestBuilder<GetAllSyncModeEnumRequestBuilder> {
    /**
     * 获取所有同步模式枚举
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SyncModeEnumKeyValueModelListResultModel>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SyncModeEnumKeyValueModelListResultModel | undefined>;
    /**
     * 获取所有同步模式枚举
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetAllSyncModeEnumRequestBuilderUriTemplate = "{+baseurl}/EnvironmentServerAPI/Enums/GetAllSyncModeEnum";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetAllSyncModeEnumRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetAllSyncModeEnumRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createSyncModeEnumKeyValueModelListResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
