/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorIRepositoryCodeAsync>d__11.MoveNext */

namespace MateralReleaseCenter.EnvironmentServer.Abstractions.Repositories;
/// <summary>
/// 配置项仓储
/// </summary>

public partial interface IConfigurationItemRepository : IEnvironmentServerRepository<ConfigurationItem>

{
}
