/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDeployListDTOListResultModelFromDiscriminatorValue, type DeployListDTOListResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ServerCenterAPI/Server/GetDeployList
 */
export interface GetDeployListRequestBuilder extends BaseRequestBuilder<GetDeployListRequestBuilder> {
    /**
     * 获得发布程序列表
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DeployListDTOListResultModel>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DeployListDTOListResultModel | undefined>;
    /**
     * 获得发布程序列表
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetDeployListRequestBuilderUriTemplate = "{+baseurl}/ServerCenterAPI/Server/GetDeployList";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetDeployListRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetDeployListRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createDeployListDTOListResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
