/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorRepositoryImplCodeAsync>d__12.MoveNext */

namespace MateralReleaseCenter.DeployServer.Repository.Repositories;
/// <summary>
/// 默认数据仓储
/// </summary>

public partial class DefaultDataRepositoryImpl(DeployServerDBContext dbContext) : DeployServerRepositoryImpl<DefaultData>(dbContext), IDefaultDataRepository, IScopedDependency<IDefaultDataRepository>
{

}
