/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorRepositoryImplCodeAsync>d__12.MoveNext */

namespace MateralReleaseCenter.DeployServer.Repository.Repositories;
/// <summary>
/// 全局参数仓储
/// </summary>

public partial class GlobalParameterRepositoryImpl(DeployServerDBContext dbContext) : DeployServerRepositoryImpl<GlobalParameter>(dbContext), IGlobalParameterRepository, IScopedDependency<IGlobalParameterRepository>
{

}
