/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorRepositoryImplCodeAsync>d__12.MoveNext */

namespace MateralReleaseCenter.DeployServer.Repository.Repositories;
/// <summary>
/// 全局环境变量仓储
/// </summary>

public partial class GlobalEnvironmentRepositoryImpl(DeployServerDBContext dbContext) : DeployServerRepositoryImpl<GlobalEnvironment>(dbContext), IGlobalEnvironmentRepository, IScopedDependency<IGlobalEnvironmentRepository>
{

}
