/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, type ResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/StartAll
 */
export interface StartAllRequestBuilder extends BaseRequestBuilder<StartAllRequestBuilder> {
    /**
     * 全部启动
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ResultModel | undefined>;
    /**
     * 全部启动
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const StartAllRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/StartAll";
/**
 * Metadata for all the requests in the request builder.
 */
export const StartAllRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: StartAllRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
