/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultModelFromDiscriminatorValue, type ResultModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeployServerAPI/ApplicationInfo/ApplyFile
 */
export interface ApplyFileRequestBuilder extends BaseRequestBuilder<ApplyFileRequestBuilder> {
    /**
     * 应用文件
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResultModel>}
     */
     put(requestConfiguration?: RequestConfiguration<ApplyFileRequestBuilderPutQueryParameters> | undefined) : Promise<ResultModel | undefined>;
    /**
     * 应用文件
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(requestConfiguration?: RequestConfiguration<ApplyFileRequestBuilderPutQueryParameters> | undefined) : RequestInformation;
}
/**
 * 应用文件
 */
export interface ApplyFileRequestBuilderPutQueryParameters {
    fileName?: string;
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const ApplyFileRequestBuilderUriTemplate = "{+baseurl}/DeployServerAPI/ApplicationInfo/ApplyFile{?fileName*,id*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ApplyFileRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: ApplyFileRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResultModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
